"use client";

import type { ReactNode } from "react";

// ============================================================================
// Khotan API helpers — typed fetch + graceful error/empty UI states
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file is yours. Every khotan dashboard component imports `khotanFetch`
// and `<ApiErrorState>` from here so that 401 (auth), 403, 404, 5xx, and
// network failures render a simple, consistent UI instead of a blank screen
// or a thrown error. Restyle it however you like.
// ============================================================================

/**
 * Error thrown by {@link khotanFetch} when a request fails. Carries the HTTP
 * status so the UI can branch on it. `status === 0` means a network-level
 * failure (server unreachable) rather than an HTTP error response.
 */
export class KhotanApiError extends Error {
  readonly status: number;
  readonly statusText: string;
  readonly body: unknown;

  constructor(status: number, statusText: string, body?: unknown) {
    super(
      status === 0
        ? "Could not reach the server"
        : `Request failed: ${String(status)} ${statusText}`,
    );
    this.name = "KhotanApiError";
    this.status = status;
    this.statusText = statusText;
    this.body = body;
  }
}

export function isKhotanApiError(error: unknown): error is KhotanApiError {
  return error instanceof KhotanApiError;
}

/**
 * `fetch` wrapper that throws a typed {@link KhotanApiError} on any non-2xx
 * response (or network failure) and returns parsed JSON otherwise. Use it for
 * every call to the khotan API so error handling stays consistent.
 */
export async function khotanFetch<T = unknown>(
  input: string,
  init?: RequestInit,
): Promise<T> {
  let res: Response;
  try {
    res = await fetch(input, init);
  } catch (err) {
    throw new KhotanApiError(
      0,
      "Network Error",
      err instanceof Error ? err.message : undefined,
    );
  }

  if (!res.ok) {
    let body: unknown;
    try {
      body = await res.clone().json();
    } catch {
      try {
        body = await res.text();
      } catch {
        body = undefined;
      }
    }
    throw new KhotanApiError(res.status, res.statusText, body);
  }

  if (res.status === 204) return undefined as T;

  try {
    return (await res.json()) as T;
  } catch {
    return undefined as T;
  }
}

interface ErrorCopy {
  /** HTTP status code, or null for non-HTTP failures. */
  code: number | null;
  title: string;
  message: string;
  /** Auth errors (401/403) show a lock icon instead of the alert icon. */
  isAuth: boolean;
}

function describeError(error: unknown): ErrorCopy {
  const status = isKhotanApiError(error) ? error.status : null;

  if (status === 401 || status === 403) {
    return {
      code: status,
      title: "Access denied",
      message: "You don't have permission to view this.",
      isAuth: true,
    };
  }
  if (status === 404) {
    return {
      code: 404,
      title: "Not found",
      message: "This resource doesn't exist.",
      isAuth: false,
    };
  }
  if (status === 429) {
    return {
      code: 429,
      title: "Too many requests",
      message: "Slow down and try again in a moment.",
      isAuth: false,
    };
  }
  if (status !== null && status >= 500) {
    return {
      code: status,
      title: "Server error",
      message: "Something went wrong on the server.",
      isAuth: false,
    };
  }
  if (status !== null && status >= 400) {
    return {
      code: status,
      title: "Request error",
      message: "The request couldn't be completed.",
      isAuth: false,
    };
  }
  return {
    code: null,
    title: "Connection error",
    message: "Couldn't reach the server.",
    isAuth: false,
  };
}

function LockIcon({ className = "" }: { className?: string }): ReactNode {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      className={className}
    >
      <rect x="3.5" y="10.5" width="17" height="10" rx="2" />
      <path d="M7.5 10.5V7a4.5 4.5 0 0 1 9 0v3.5" />
      <circle cx="12" cy="15.5" r="1.25" />
    </svg>
  );
}

function AlertIcon({ className = "" }: { className?: string }): ReactNode {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      className={className}
    >
      <circle cx="12" cy="12" r="9" />
      <path d="M12 8v5" />
      <path d="M12 16.5h.01" />
    </svg>
  );
}

export interface ApiErrorStateProps {
  error: unknown;
  /** Called when the user clicks Retry. Omit to hide the Retry button. */
  onRetry?: () => void;
  /** Render a smaller inline banner (for nested panels) instead of a full card. */
  compact?: boolean;
  className?: string;
}

/**
 * Simple UI for a failed khotan API request — shows an icon, the HTTP status,
 * and a short message, plus an optional Retry button. Intentionally minimal.
 */
export function ApiErrorState({
  error,
  onRetry,
  compact = false,
  className = "",
}: ApiErrorStateProps): ReactNode {
  const { code, title, message, isAuth } = describeError(error);
  const Icon = isAuth ? LockIcon : AlertIcon;

  if (compact) {
    return (
      <div
        role="alert"
        className={`flex flex-wrap items-center justify-between gap-2 rounded-md border border-border bg-muted/30 px-3 py-2 ${className}`}
      >
        <span className="flex items-center gap-2 text-xs font-medium text-foreground">
          <Icon className="h-4 w-4 text-muted-foreground" />
          {code ? `${String(code)} — ${title}` : title}
        </span>
        {onRetry && (
          <button
            type="button"
            onClick={onRetry}
            className="text-xs text-muted-foreground underline-offset-2 hover:underline"
          >
            Retry
          </button>
        )}
      </div>
    );
  }

  return (
    <div
      role="alert"
      className={`flex flex-col items-center justify-center rounded-lg border border-border bg-card px-6 py-12 text-center ${className}`}
    >
      <Icon className="h-8 w-8 text-muted-foreground" />
      <p className="mt-3 text-sm font-medium text-foreground">
        {code ? `${String(code)} — ${title}` : title}
      </p>
      <p className="mt-1 text-sm text-muted-foreground">{message}</p>
      {onRetry && (
        <button
          type="button"
          onClick={onRetry}
          className="mt-4 text-xs text-muted-foreground underline-offset-2 hover:underline"
        >
          Retry
        </button>
      )}
    </div>
  );
}
