// ============================================================================
// App Auth — Better Auth config plus the khotan management API authorize hook
// Generated by khotan CLI · https://github.com/khotan-data
// ============================================================================

import { betterAuth } from "better-auth";
import { genericOAuth, oAuthProxy } from "better-auth/plugins";

function commaList(value: string | undefined): string[] {
  return (value ?? "")
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}

export const auth = betterAuth({
  plugins: [
    genericOAuth({
      config: [
        {
          providerId: process.env.AUTH_GENERIC_PROVIDER_ID ?? "generic",
          clientId: process.env.AUTH_GENERIC_CLIENT_ID ?? "",
          clientSecret: process.env.AUTH_GENERIC_CLIENT_SECRET ?? "",
          discoveryUrl: process.env.AUTH_GENERIC_DISCOVERY_URL ?? "",
          scopes: commaList(process.env.AUTH_GENERIC_SCOPES).length
            ? commaList(process.env.AUTH_GENERIC_SCOPES)
            : ["openid", "profile", "email"],
        },
      ],
    }),
    oAuthProxy(),
  ],
});

export async function authorizeKhotanRequest(
  request: Request,
): Promise<boolean> {
  const session = await auth.api.getSession({ headers: request.headers });
  if (!session?.user) return false;

  const allowedEmails = commaList(process.env.KHOTAN_ADMIN_EMAILS).map(
    (email) => email.toLowerCase(),
  );
  if (allowedEmails.length === 0) return true;

  const email = session.user.email;
  return typeof email === "string" && allowedEmails.includes(email.toLowerCase());
}
