// ============================================================================
// Cache — durable sync-state storage for flows, relays, and webhooks
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file defines the cache() builder and types. Create named cache
// definitions for expensive upstream snapshots, checkpoints, and dedupe markers,
// then register them in your khotan.ts factory config.
// ============================================================================

import type { CacheRegistration, CacheScope } from "khotan-data/factory";

export interface CacheConfig {
  /** Unique cache name used by runtime helpers and DB registration */
  name: string;
  /** Optional ownership metadata for humans and runtime validation */
  scope?: CacheScope;
  /** Optional default TTL like "30m", "6h", or 86400 */
  ttl?: string | number;
}

export function cache(config: CacheConfig): CacheRegistration {
  return {
    name: config.name,
    scope: config.scope,
    ttl: config.ttl,
  };
}

// ---------------------------------------------------------------------------
// Usage Example (create a file like caches/cin7-products-snapshot.ts)
// ---------------------------------------------------------------------------
//
// import { cache } from "./cache";
//
// export const cin7ProductsSnapshotCache = cache({
//   name: "cin7-products-snapshot",
//   scope: {
//     plug: "cin7",
//     resource: "products",
//     flow: "cin7-to-pollinate-products-relay",
//   },
//   ttl: "6h",
// });
//
// Then register in your khotan config:
//
// import { cin7ProductsSnapshotCache } from "./caches/cin7-products-snapshot";
//
// const khotanData = khotan({
//   adapter: drizzleAdapter(db),
//   caches: [cin7ProductsSnapshotCache],
//   plugs: [...],
// });
//
// Flow, relay, catch, and pass workflows can then use:
//   await khotanCache(ctx, "cin7-products-snapshot").get("all-products");
//   await khotanCache(ctx, "cin7-products-snapshot").set("all-products", payload);
//   await khotanCache(ctx, "cin7-products-snapshot").delete("all-products");
