// ============================================================================
// Catch — durable webhook event processing via Vercel Workflow
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file keeps local imports stable while reusing the real builder and types
// from khotan-data/factory. Create per-service catch files using catchEvent()
// to handle verified webhook events with durable, retryable workflow steps.
// ============================================================================

export { catchEvent } from "khotan-data/factory";

export type {
  CatchConfig,
  CatchRegistration,
  CatchWorkflowContext as CatchContext,
} from "khotan-data/factory";

export type CatchWorkflow<
  TEvent extends Record<string, unknown> = Record<string, unknown>,
> = (
  ctx: import("khotan-data/factory").CatchWorkflowContext<TEvent>,
) => Promise<void>;

// ---------------------------------------------------------------------------
// Usage Example (create a file like webhooks/pollinate-catch.ts)
// ---------------------------------------------------------------------------
//
// import { khotanCache } from "khotan-data/factory";
// import { z } from "zod";
// import { catchEvent, type CatchContext } from "./catch";
// Khotan already records webhook deliveries in khotan_webhook_events and links
// them to khotan_runs. Use your catch workflow for app-specific side effects
// and optionally khotanCache(ctx, "name") for dedupe or cursor state.
//
// Declare "use step" functions at MODULE TOP LEVEL and pass them serializable
// values only (`ctx` is plain data). Do NOT nest steps inside the "use workflow"
// function — closures over workflow scope cannot be hoisted and fail at runtime.
//
// // Step: top-level, full Node.js access, retried independently.
// const pollinateEventSchema = z.object({
//   id: z.string().optional(),
//   data: z.object({ orderId: z.string() }),
// });
//
// type PollinateEvent = z.infer<typeof pollinateEventSchema>;
//
// async function notifyOps(ctx: CatchContext<PollinateEvent>) {
//   "use step";
//   const cache = khotanCache(ctx, "pollinate-webhook-markers");
//   const eventId = ctx.event.id ?? "";
//   if (eventId && (await cache.get<boolean>(eventId))) return;
//
//   console.log("Handled webhook", {
//     eventType: ctx.eventType,
//     orderId: ctx.event.data.orderId,
//     khotanRunId: ctx.khotanRunId,
//   });
//
//   if (eventId) {
//     await cache.set(eventId, true);
//   }
// }
//
// // Workflow: orchestration only.
// async function pollinateCatchWorkflow(ctx: CatchContext) {
//   "use workflow";
//   await notifyOps(ctx);
// }
//
// export const pollinateCatch = catchEvent({
//   name: "pollinate-orders",
//   events: ["order.created"],
//   schema: pollinateEventSchema,
//   workflow: pollinateCatchWorkflow,
// });
//
// Then register in your khotan config:
//
// plugs: [{
//   name: "pollinate",
//   plug: pollinatePlug,
//   wires: [pollinateWire],
//   catches: [pollinateCatch],
// }]
