// ============================================================================
// Catch — durable webhook event processing via Vercel Workflow
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file defines the catchEvent() builder and types. Create per-service
// catch files (e.g. pollinate-catch.ts) using this builder to handle verified
// webhook events with durable, retryable workflow steps.
//
// Catch workflows receive a CatchContext with the parsed event payload,
// event type, and headers. Steps have full Node.js access — import your
// own db, services, etc.
// ============================================================================

// ---------------------------------------------------------------------------
// Schema helpers — Zod schemas satisfy this shape without importing Zod here
// ---------------------------------------------------------------------------

export interface EventSchema<TEvent> {
  parse(input: unknown): TEvent;
}

export type EventFromSchema<TSchema> =
  TSchema extends EventSchema<infer TEvent> ? TEvent : Record<string, unknown>;

// ---------------------------------------------------------------------------
// Context — serializable data passed to the workflow
// ---------------------------------------------------------------------------

export interface CatchContext<TEvent = Record<string, unknown>> {
  /** Parsed webhook payload */
  event: TEvent;
  /** Event type extracted from payload (e.g. "order.created") */
  eventType: string;
  /** Incoming request headers */
  headers: Record<string, string>;
  /** Khotan run ID created for this webhook handler execution */
  khotanRunId: string;
  /** Internal Khotan instance identifier for helper APIs */
  khotanInstanceId: string;
}

// ---------------------------------------------------------------------------
// Workflow type — the function signature your workflow must conform to
// ---------------------------------------------------------------------------

export type CatchWorkflow<TEvent> = (
  ctx: CatchContext<TEvent>,
) => Promise<void>;

// ---------------------------------------------------------------------------
// Config — passed to the catchEvent() builder
// ---------------------------------------------------------------------------

export interface CatchConfig<
  TSchema extends EventSchema<unknown> | undefined = undefined,
> {
  /** Unique name for this catch handler (used for DB tracking and Hub display) */
  name: string;
  /** Event types this catch should receive */
  events?: string[];
  /** Optional schema that validates and types ctx.event for the workflow */
  schema?: TSchema;
  /** Workflow function that processes the event */
  workflow: CatchWorkflow<EventFromSchema<TSchema>>;
}

// ---------------------------------------------------------------------------
// Registration — returned by catchEvent(), consumed by factory config
// ---------------------------------------------------------------------------

export interface CatchRegistration<
  TSchema extends EventSchema<unknown> | undefined = undefined,
> {
  type: "catch";
  name: string;
  events?: string[];
  schema?: TSchema;
  workflow: CatchWorkflow<EventFromSchema<TSchema>>;
}

// ---------------------------------------------------------------------------
// Builder
// ---------------------------------------------------------------------------

export function catchEvent<
  TSchema extends EventSchema<unknown> | undefined = undefined,
>(config: CatchConfig<TSchema>): CatchRegistration<TSchema> {
  const registration: CatchRegistration<TSchema> = {
    type: "catch",
    name: config.name,
    workflow: config.workflow,
  };
  if (config.events) {
    registration.events = config.events;
  }
  if (config.schema) {
    registration.schema = config.schema;
  }
  return registration;
}

// ---------------------------------------------------------------------------
// Usage Example (create a file like webhooks/pollinate-catch.ts)
// ---------------------------------------------------------------------------
//
// import { khotanCache } from "khotan-data/factory";
// import { z } from "zod";
// import { catchEvent, type CatchContext } from "./catch";
// Khotan already records webhook deliveries in khotan_webhook_events and links
// them to khotan_runs. Use your catch workflow for app-specific side effects
// and optionally khotanCache(ctx, "name") for dedupe or cursor state.
//
// Declare "use step" functions at MODULE TOP LEVEL and pass them serializable
// values only (`ctx` is plain data). Do NOT nest steps inside the "use workflow"
// function — closures over workflow scope cannot be hoisted and fail at runtime.
//
// // Step: top-level, full Node.js access, retried independently.
// const pollinateEventSchema = z.object({
//   id: z.string().optional(),
//   data: z.object({ orderId: z.string() }),
// });
//
// type PollinateEvent = z.infer<typeof pollinateEventSchema>;
//
// async function notifyOps(ctx: CatchContext<PollinateEvent>) {
//   "use step";
//   const cache = khotanCache(ctx, "pollinate-webhook-markers");
//   const eventId = ctx.event.id ?? "";
//   if (eventId && (await cache.get<boolean>(eventId))) return;
//
//   console.log("Handled webhook", {
//     eventType: ctx.eventType,
//     orderId: ctx.event.data.orderId,
//     khotanRunId: ctx.khotanRunId,
//   });
//
//   if (eventId) {
//     await cache.set(eventId, true);
//   }
// }
//
// // Workflow: orchestration only.
// async function pollinateCatchWorkflow(ctx: CatchContext) {
//   "use workflow";
//   await notifyOps(ctx);
// }
//
// export const pollinateCatch = catchEvent({
//   name: "pollinate-orders",
//   events: ["order.created"],
//   schema: pollinateEventSchema,
//   workflow: pollinateCatchWorkflow,
// });
//
// Then register in your khotan config:
//
// plugs: [{
//   name: "pollinate",
//   plug: pollinatePlug,
//   wires: [pollinateWire],
//   catches: [pollinateCatch],
// }]
