// ============================================================================
// Example: Catch
// Generated by khotan CLI · https://github.com/khotan-data
//
// Copy this file, rename it for your webhook source/event, and register the
// exported catch handler in {outputDir}/khotan.ts.
// ============================================================================

import { catchEvent, type CatchContext } from "./catch";

async function stripeInvoiceCatchWorkflow(ctx: CatchContext) {
  "use workflow";

  async function persistEvent() {
    "use step";
    console.log("Handling webhook event", {
      eventType: ctx.eventType,
      khotanRunId: ctx.khotanRunId,
    });

    // Khotan already records webhook deliveries. Add app-specific side effects
    // here, such as updating a local table or enqueueing downstream work.
    console.log("Webhook payload", {
      event: ctx.event,
      headers: ctx.headers,
    });
  }

  await persistEvent();
}

export const stripeInvoiceCatch = catchEvent({
  name: "stripe-invoices",
  events: ["invoice.paid"],
  workflow: stripeInvoiceCatchWorkflow,
});
