"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

// ============================================================================
// Debug Index — Lists all registered plugs for debugging
// Generated by khotan CLI · https://github.com/khotan-data
//
// Place at: app/debug/page.tsx
// Requires KHOTAN_DEBUG env var to be set for the debug route to respond.
// ============================================================================

interface Plug {
  id: string;
  name: string;
  baseUrl: string;
  authType: string;
  status: "connected" | "error" | "idle";
}

export default function DebugIndexPage() {
  const [plugs, setPlugs] = useState<Plug[]>([]);
  const [loading, setLoading] = useState(true);
  const [debugEnabled, setDebugEnabled] = useState<boolean | null>(null);

  useEffect(() => {
    Promise.all([
      fetch("/api/khotan/debug").then((r) => r.ok),
      fetch("/api/khotan/plugs").then((r) => (r.ok ? r.json() : [])),
    ])
      .then(([enabled, data]) => {
        setDebugEnabled(enabled);
        setPlugs(data as Plug[]);
      })
      .catch(() => setDebugEnabled(false))
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <main className="container mx-auto max-w-3xl px-4 py-10">
        <div className="h-8 w-48 animate-pulse rounded bg-muted" />
      </main>
    );
  }

  if (!debugEnabled) {
    return (
      <main className="container mx-auto max-w-3xl px-4 py-10">
        <h1 className="text-2xl font-bold tracking-tight mb-4">Debug</h1>
        <p className="text-muted-foreground">
          Debug mode is not enabled. Set{" "}
          <code className="bg-muted px-1.5 py-0.5 rounded text-sm">
            KHOTAN_DEBUG=1
          </code>{" "}
          in your environment and restart the server.
        </p>
      </main>
    );
  }

  return (
    <main className="container mx-auto max-w-3xl px-4 py-10">
      <div className="mb-6">
        <a
          href="/config"
          className="text-sm text-muted-foreground hover:text-foreground"
        >
          ← Back to Hub
        </a>
      </div>
      <h1 className="text-2xl font-bold tracking-tight mb-6">Debug</h1>
      <p className="text-muted-foreground mb-6">
        Select a plug to test requests through its real code path.
      </p>
      <div className="grid gap-3">
        {plugs.map((plug) => (
          <Link
            key={plug.id}
            href={`/debug/${plug.name}`}
            className="flex items-center justify-between rounded-lg border border-border p-4 transition-colors hover:border-foreground/30 hover:bg-muted/50"
          >
            <div>
              <p className="font-medium">{plug.name}</p>
              <p className="text-xs text-muted-foreground truncate">
                {plug.baseUrl}
              </p>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-xs text-muted-foreground">
                {plug.authType}
              </span>
              <span className="text-muted-foreground">→</span>
            </div>
          </Link>
        ))}
      </div>
    </main>
  );
}
