"use client";

import { useParams } from "next/navigation";
import { PlugDebugger } from "@/components/khotan/plug-debugger";

// ============================================================================
// Debug Page — Route for plug debugging
// Generated by khotan CLI · https://github.com/khotan-data
//
// Place at: app/debug/[plugName]/page.tsx
// Requires KHOTAN_DEBUG env var to be set for the debug route to respond.
// ============================================================================

export default function PlugDebugPage() {
  const params = useParams<{ plugName: string }>();
  const plugName = params.plugName;

  if (!plugName) {
    return (
      <main className="container mx-auto max-w-6xl px-4 py-10">
        <p className="text-muted-foreground">No plug specified.</p>
      </main>
    );
  }

  return (
    <main className="container mx-auto max-w-6xl px-4 py-10">
      <div className="flex items-center justify-between mb-6">
        <a
          href="/debug"
          className="text-sm text-muted-foreground hover:text-foreground"
        >
          ← All Plugs
        </a>
        <a
          href="/config"
          className="text-xs text-muted-foreground hover:text-foreground"
        >
          Hub
        </a>
      </div>
      <h1 className="text-2xl font-bold tracking-tight mb-6">
        Debug: {plugName}
      </h1>
      <PlugDebugger plugName={plugName} />
    </main>
  );
}
