"use client";

import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Switch } from "@/components/ui/switch";
import { Button } from "@/components/ui/button";
import { WirePanel } from "./wire";
import { VarPanel } from "./var-panel";
import { khotanFetch, ApiErrorState } from "./api-state";

// ============================================================================
// Khotan Hub — Dashboard for configured plugs and flows
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file is yours. Restyle, extend, or embed it however you like.
// It uses shadcn/ui primitives and fetches from /api/khotan.
// ============================================================================

interface Plug {
  id: string;
  name: string;
  baseUrl: string;
  authType: string;
  enabled: boolean;
  status: "connected" | "error" | "idle";
  statusMessage: string | null;
  flowCount: number;
  createdAt: string;
  updatedAt: string;
}

interface Flow {
  id: string;
  plugId: string;
  name: string;
  type: "inflow" | "outflow" | "relay" | "webhook";
  enabled: boolean;
  schedule: string | null;
  lastRunAt: string | null;
  lastRunStatus:
    | "pending"
    | "running"
    | "completed"
    | "partial"
    | "failed"
    | "cancelled"
    | null;
  plugName: string | null;
  to?: string | null;
  destinationPlugId?: string | null;
  destinationPlugName?: string | null;
}

interface WebhookHandler {
  id: string;
  wireId: string;
  name: string;
  type: "catch" | "pass";
  destinationPlugId: string | null;
  events: string[] | null;
  enabled: boolean;
  lastRunAt: string | null;
  lastRunStatus:
    | "pending"
    | "running"
    | "completed"
    | "partial"
    | "failed"
    | "cancelled"
    | null;
  createdAt: string;
  updatedAt: string;
}

type StatusVariant = "default" | "secondary" | "destructive" | "outline";
type FlowTypeVariant = "default" | "secondary" | "outline";

const statusVariant: Record<string, StatusVariant> = {
  connected: "default",
  idle: "secondary",
  error: "destructive",
};

const flowTypeVariant: Record<string, FlowTypeVariant> = {
  inflow: "default",
  outflow: "secondary",
  relay: "outline",
  webhook: "outline",
};

const runStatusVariant: Record<string, StatusVariant> = {
  pending: "outline",
  running: "secondary",
  completed: "default",
  partial: "secondary",
  failed: "destructive",
  cancelled: "outline",
};

export function KhotanHub({
  webhookUrl,
  debugHref,
  logsHref,
}: {
  webhookUrl?: string;
  debugHref?: (plugName: string) => string;
  /** When set, shows an "Open Logs" button linking here. Hidden if omitted. */
  logsHref?: string;
} = {}) {
  const [plugs, setPlugs] = useState<Plug[]>([]);
  const [flows, setFlows] = useState<Flow[]>([]);
  const [webhookHandlers, setWebhookHandlers] = useState<WebhookHandler[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<unknown>(null);
  const [selectedPlugId, setSelectedPlugId] = useState<string | null>(null);
  const [debugEnabled, setDebugEnabled] = useState(false);
  const [runningFlowId, setRunningFlowId] = useState<string | null>(null);
  const [runNotice, setRunNotice] = useState<{
    type: "ok" | "error";
    text: string;
  } | null>(null);

  useEffect(() => {
    fetch("/api/khotan/debug")
      .then((res) => setDebugEnabled(res.ok))
      .catch(() => setDebugEnabled(false));
  }, []);

  async function fetchData() {
    setLoading(true);
    setError(null);
    try {
      const [plugsData, flowsData] = await Promise.all([
        khotanFetch<Plug[]>("/api/khotan/plugs"),
        khotanFetch<Flow[]>("/api/khotan/flows"),
      ]);
      setPlugs(plugsData);
      setFlows(flowsData);
    } catch (err) {
      setError(err);
    } finally {
      setLoading(false);
    }
  }

  async function toggleFlow(flowId: string, enabled: boolean) {
    setFlows((prev) =>
      prev.map((flow) => (flow.id === flowId ? { ...flow, enabled } : flow)),
    );
    await fetch(`/api/khotan/flows/${flowId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ enabled }),
    });
  }

  async function runFlow(flowId: string, flowName: string) {
    setRunningFlowId(flowId);
    setRunNotice(null);
    try {
      const res = await fetch(`/api/khotan/flows/${flowId}/runs`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ variant: "default" }),
      });
      if (!res.ok) {
        const data = (await res.json().catch(() => ({}))) as {
          error?: string;
          hint?: string;
        };
        setRunNotice({
          type: "error",
          text: data.hint ?? data.error ?? `Failed to trigger ${flowName}.`,
        });
        return;
      }
      setRunNotice({ type: "ok", text: `Triggered ${flowName}.` });
      await fetchData();
    } catch {
      setRunNotice({ type: "error", text: `Failed to trigger ${flowName}.` });
    } finally {
      setRunningFlowId(null);
    }
  }

  async function toggleWebhookHandler(handlerId: string, enabled: boolean) {
    setWebhookHandlers((prev) =>
      prev.map((h) => (h.id === handlerId ? { ...h, enabled } : h)),
    );
    await fetch(`/api/khotan/webhook-handlers/${handlerId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ enabled }),
    });
  }

  useEffect(() => {
    fetchData();
  }, []);

  useEffect(() => {
    if (!selectedPlugId) {
      setWebhookHandlers([]);
      return;
    }
    const plug = plugs.find((p) => p.id === selectedPlugId);
    if (!plug) return;
    fetch(`/api/khotan/webhook-handlers/${plug.name}`)
      .then((res) => (res.ok ? res.json() : []))
      .then((data) => setWebhookHandlers(data))
      .catch(() => setWebhookHandlers([]));
  }, [selectedPlugId, plugs]);

  if (loading) {
    return (
      <div className="space-y-4">
        <div className="h-8 w-48 animate-pulse rounded bg-muted" />
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {[1, 2, 3].map((i) => (
            <Card key={i}>
              <CardHeader>
                <div className="h-5 w-32 animate-pulse rounded bg-muted" />
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <div className="h-4 w-full animate-pulse rounded bg-muted" />
                  <div className="h-4 w-2/3 animate-pulse rounded bg-muted" />
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    );
  }

  if (error) {
    return <ApiErrorState error={error} onRetry={fetchData} />;
  }

  if (plugs.length === 0) {
    return (
      <Card>
        <CardContent className="py-8 text-center">
          <p className="text-muted-foreground mb-2">No plugs configured yet.</p>
          <p className="text-sm text-muted-foreground">
            Register plugs in your <code>khotan.ts</code> config file, then
            restart the dev server.
          </p>
        </CardContent>
      </Card>
    );
  }

  const selectedPlug = selectedPlugId
    ? plugs.find((p) => p.id === selectedPlugId)
    : null;
  const plugFlows = selectedPlugId
    ? flows.filter(
        (flow) =>
          flow.plugId === selectedPlugId ||
          (flow.type === "relay" && flow.destinationPlugId === selectedPlugId),
      )
    : [];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between gap-4">
        <h2 className="text-2xl font-bold tracking-tight">Khotan Hub</h2>
        {logsHref && (
          <Button
            variant="outline"
            size="sm"
            onClick={() => {
              window.location.href = logsHref;
            }}
          >
            Open Logs
          </Button>
        )}
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {plugs.map((plug) => (
          <Card
            key={plug.id}
            className={`cursor-pointer transition-all hover:border-primary ${
              selectedPlugId === plug.id
                ? "border-primary ring-2 ring-primary ring-offset-2 ring-offset-background shadow-md"
                : "border-border"
            }`}
            onClick={() =>
              setSelectedPlugId(selectedPlugId === plug.id ? null : plug.id)
            }
          >
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">{plug.name}</CardTitle>
              <Badge variant={statusVariant[plug.status] ?? "secondary"}>
                {plug.status}
              </Badge>
            </CardHeader>
            <CardContent>
              <p className="text-xs text-muted-foreground truncate">
                {plug.baseUrl}
              </p>
              <div className="mt-2 flex items-center justify-between">
                <p className="text-xs text-muted-foreground">
                  {plug.authType} · {plug.flowCount} flow
                  {plug.flowCount !== 1 ? "s" : ""}
                </p>
                {debugEnabled && (
                  <Button
                    size="sm"
                    variant="ghost"
                    className="h-6 px-2 text-[11px]"
                    onClick={(e) => {
                      e.stopPropagation();
                      if (debugHref) {
                        window.location.href = debugHref(plug.name);
                      } else {
                        window.location.href = `/debug/${plug.name}`;
                      }
                    }}
                  >
                    Debug
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {!selectedPlug && (
        <Card className="border-dashed">
          <CardContent className="py-10 text-center">
            <p className="text-muted-foreground mb-1">No plug selected yet.</p>
            <p className="text-sm text-muted-foreground">
              Select a plug above to view its flows, webhook handlers, and
              credentials.
            </p>
          </CardContent>
        </Card>
      )}

      {selectedPlug && (
        <div className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>{selectedPlug.name} — Flows</CardTitle>
            </CardHeader>
            <CardContent>
              {runNotice && (
                <p
                  className={`mb-3 text-sm ${
                    runNotice.type === "error"
                      ? "text-destructive"
                      : "text-muted-foreground"
                  }`}
                >
                  {runNotice.text}
                </p>
              )}
              {plugFlows.length === 0 ? (
                <p className="text-sm text-muted-foreground">
                  No flows configured for this plug.
                </p>
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Name</TableHead>
                      <TableHead>Type</TableHead>
                      <TableHead>Association</TableHead>
                      <TableHead>Schedule</TableHead>
                      <TableHead>Last Run</TableHead>
                      <TableHead>Enabled</TableHead>
                      <TableHead className="text-right">Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {plugFlows.map((flow) => (
                      <TableRow key={flow.id}>
                        <TableCell className="font-medium">
                          {flow.name}
                        </TableCell>
                        <TableCell>
                          <Badge
                            variant={flowTypeVariant[flow.type] ?? "outline"}
                          >
                            {flow.type}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-muted-foreground">
                          {flow.plugId === selectedPlug.id
                            ? flow.destinationPlugName
                              ? `to ${flow.destinationPlugName}`
                              : "registered here"
                            : `from ${flow.plugName ?? "source"}`}
                        </TableCell>
                        <TableCell className="text-muted-foreground">
                          {flow.schedule ?? "—"}
                        </TableCell>
                        <TableCell>
                          {flow.lastRunStatus ? (
                            <Badge
                              variant={
                                runStatusVariant[flow.lastRunStatus] ??
                                "secondary"
                              }
                            >
                              {flow.lastRunStatus}
                            </Badge>
                          ) : (
                            <span className="text-muted-foreground">never</span>
                          )}
                        </TableCell>
                        <TableCell>
                          <Switch
                            checked={flow.enabled}
                            onCheckedChange={(v) => toggleFlow(flow.id, v)}
                          />
                        </TableCell>
                        <TableCell className="text-right">
                          <Button
                            size="sm"
                            variant="outline"
                            className="h-7 px-2 text-xs"
                            disabled={runningFlowId !== null}
                            onClick={() => runFlow(flow.id, flow.name)}
                          >
                            {runningFlowId === flow.id ? "Running…" : "Run now"}
                          </Button>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              )}
            </CardContent>
          </Card>

          {webhookHandlers.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle>{selectedPlug.name} — Webhook Handlers</CardTitle>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Name</TableHead>
                      <TableHead>Type</TableHead>
                      <TableHead>Events</TableHead>
                      <TableHead>Destination</TableHead>
                      <TableHead>Last Run</TableHead>
                      <TableHead>Enabled</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {webhookHandlers.map((handler) => (
                      <TableRow key={handler.id}>
                        <TableCell className="font-medium">
                          {handler.name}
                        </TableCell>
                        <TableCell>
                          <Badge
                            variant={
                              handler.type === "catch" ? "default" : "secondary"
                            }
                          >
                            {handler.type}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-muted-foreground">
                          {handler.events?.length
                            ? handler.events.join(", ")
                            : "from wire config"}
                        </TableCell>
                        <TableCell className="text-muted-foreground">
                          {handler.destinationPlugId
                            ? (plugs.find(
                                (p) => p.id === handler.destinationPlugId,
                              )?.name ?? handler.destinationPlugId)
                            : "—"}
                        </TableCell>
                        <TableCell>
                          {handler.lastRunStatus ? (
                            <Badge
                              variant={
                                runStatusVariant[handler.lastRunStatus] ??
                                "secondary"
                              }
                            >
                              {handler.lastRunStatus}
                            </Badge>
                          ) : (
                            <span className="text-muted-foreground">never</span>
                          )}
                        </TableCell>
                        <TableCell>
                          <Switch
                            checked={handler.enabled}
                            onCheckedChange={(v) =>
                              toggleWebhookHandler(handler.id, v)
                            }
                          />
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          )}

          <VarPanel plugName={selectedPlug.name} />
          <WirePanel plugName={selectedPlug.name} webhookUrl={webhookUrl} />
        </div>
      )}
    </div>
  );
}
