"use client";

import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Switch } from "@/components/ui/switch";

// ============================================================================
// Khotan Hub — Dashboard for configured plugs and syncs
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file is yours. Restyle, extend, or embed it however you like.
// It uses shadcn/ui primitives and fetches from /api/khotan.
// ============================================================================

interface Plug {
  id: string;
  name: string;
  baseUrl: string;
  authType: string;
  enabled: boolean;
  status: "connected" | "error" | "idle";
  statusMessage: string | null;
  syncCount: number;
  createdAt: string;
  updatedAt: string;
}

interface Sync {
  id: string;
  plugId: string;
  name: string;
  type: "inflow" | "outflow" | "relay" | "webhook";
  enabled: boolean;
  schedule: string | null;
  lastRunAt: string | null;
  lastRunStatus: "ok" | "failed" | null;
  plugName: string | null;
}

type StatusVariant = "default" | "secondary" | "destructive" | "outline";
type SyncTypeVariant = "default" | "secondary" | "outline";

const statusVariant: Record<string, StatusVariant> = {
  connected: "default",
  idle: "secondary",
  error: "destructive",
};

const syncTypeVariant: Record<string, SyncTypeVariant> = {
  inflow: "default",
  outflow: "secondary",
  relay: "outline",
  webhook: "outline",
};

export function KhotanHub() {
  const [plugs, setPlugs] = useState<Plug[]>([]);
  const [syncs, setSyncs] = useState<Sync[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedPlugId, setSelectedPlugId] = useState<string | null>(null);

  async function fetchData() {
    setLoading(true);
    setError(null);
    try {
      const [plugsRes, syncsRes] = await Promise.all([
        fetch("/api/khotan/plugs"),
        fetch("/api/khotan/syncs"),
      ]);
      if (!plugsRes.ok || !syncsRes.ok) {
        throw new Error("Failed to fetch khotan data");
      }
      setPlugs(await plugsRes.json());
      setSyncs(await syncsRes.json());
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    fetchData();
  }, []);

  if (loading) {
    return (
      <div className="space-y-4">
        <div className="h-8 w-48 animate-pulse rounded bg-muted" />
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {[1, 2, 3].map((i) => (
            <Card key={i}>
              <CardHeader>
                <div className="h-5 w-32 animate-pulse rounded bg-muted" />
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <div className="h-4 w-full animate-pulse rounded bg-muted" />
                  <div className="h-4 w-2/3 animate-pulse rounded bg-muted" />
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <Card>
        <CardContent className="py-8 text-center">
          <p className="text-destructive mb-4">{error}</p>
          <button
            onClick={fetchData}
            className="text-sm underline hover:no-underline"
          >
            Retry
          </button>
        </CardContent>
      </Card>
    );
  }

  if (plugs.length === 0) {
    return (
      <Card>
        <CardContent className="py-8 text-center">
          <p className="text-muted-foreground mb-2">No plugs configured yet.</p>
          <p className="text-sm text-muted-foreground">
            Register plugs in your <code>khotan.ts</code> config file, then
            restart the dev server.
          </p>
        </CardContent>
      </Card>
    );
  }

  const selectedPlug = selectedPlugId
    ? plugs.find((p) => p.id === selectedPlugId)
    : null;
  const plugSyncs = selectedPlugId
    ? syncs.filter((s) => s.plugId === selectedPlugId)
    : [];

  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-bold tracking-tight">Khotan Hub</h2>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {plugs.map((plug) => (
          <Card
            key={plug.id}
            className={`cursor-pointer transition-colors hover:border-primary ${
              selectedPlugId === plug.id ? "border-primary" : ""
            }`}
            onClick={() =>
              setSelectedPlugId(
                selectedPlugId === plug.id ? null : plug.id,
              )
            }
          >
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">
                {plug.name}
              </CardTitle>
              <Badge variant={statusVariant[plug.status] ?? "secondary"}>
                {plug.status}
              </Badge>
            </CardHeader>
            <CardContent>
              <p className="text-xs text-muted-foreground truncate">
                {plug.baseUrl}
              </p>
              <div className="mt-2 flex items-center justify-between">
                <span className="text-xs text-muted-foreground">
                  {plug.authType} · {plug.syncCount} sync
                  {plug.syncCount !== 1 ? "s" : ""}
                </span>
                <Switch checked={plug.enabled} disabled />
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {selectedPlug && (
        <Card>
          <CardHeader>
            <CardTitle>{selectedPlug.name} — Syncs</CardTitle>
          </CardHeader>
          <CardContent>
            {plugSyncs.length === 0 ? (
              <p className="text-sm text-muted-foreground">
                No syncs configured for this plug.
              </p>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Name</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Schedule</TableHead>
                    <TableHead>Last Run</TableHead>
                    <TableHead>Enabled</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {plugSyncs.map((sync) => (
                    <TableRow key={sync.id}>
                      <TableCell className="font-medium">
                        {sync.name}
                      </TableCell>
                      <TableCell>
                        <Badge
                          variant={
                            syncTypeVariant[sync.type] ?? "outline"
                          }
                        >
                          {sync.type}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-muted-foreground">
                        {sync.schedule ?? "—"}
                      </TableCell>
                      <TableCell>
                        {sync.lastRunStatus ? (
                          <Badge
                            variant={
                              sync.lastRunStatus === "ok"
                                ? "default"
                                : "destructive"
                            }
                          >
                            {sync.lastRunStatus}
                          </Badge>
                        ) : (
                          <span className="text-muted-foreground">
                            never
                          </span>
                        )}
                      </TableCell>
                      <TableCell>
                        <Switch checked={sync.enabled} disabled />
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
}
