// ============================================================================
// Example: Inflow
// Generated by khotan CLI · https://github.com/khotan-data
//
// Copy this file, rename it for your source service/resource, and register the
// exported flow in {outputDir}/khotan.ts.
// ============================================================================

import { db } from "@/db";
import { products } from "@/db/schema";
import { shopifyPlug } from "../plugs/shopify";
import { inflow, type InflowContext } from "./inflow";

async function shopifyProductsWorkflow(ctx: InflowContext) {
  "use workflow";

  async function extractAndLoad() {
    "use step";
    console.log("Starting inflow", {
      flow: ctx.flow.name,
      khotanRunId: ctx.khotanRunId,
      runType: ctx.runType,
    });

    const response = await shopifyPlug.get<{
      data?: Array<{ id: string; sku?: string; name?: string }>;
    }>("/products", {
      vars: ctx.vars,
    });
    const records = Array.isArray(response.data) ? response.data : [];

    if (records.length > 0) {
      await db.insert(products).values(
        records.map((record) => ({
          externalId: record.id,
          sku: record.sku ?? record.id,
          name: record.name ?? record.id,
        })),
      );
    }

    return {
      extracted: records.length,
      transformed: records.length,
      created: records.length,
      metadata: { source: ctx.flow.name },
    };
  }

  return extractAndLoad();
}

export const shopifyProductsInflow = inflow({
  name: "shopify-products-inflow",
  resource: "products",
  schedule: "0 * * * *",
  workflow: shopifyProductsWorkflow,
});
