// ============================================================================
// Inflow — durable external service → app data movement
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file defines the inflow() builder and types. Create per-service flow
// files (e.g. shopify-products.ts) using this builder to pull records from an
// external service, transform them, and load them into your app with durable,
// retryable Vercel Workflow steps. Inflow workflows can also use
// khotanCache(ctx, "name") for checkpoints and last-seen markers across runs.
// ============================================================================

import type {
  FlowRegistration,
  FlowRunResult,
  FlowWorkflowContext,
} from "khotan-data/factory";

export type InflowContext = FlowWorkflowContext & {
  flow: FlowWorkflowContext["flow"] & { type: "inflow" };
};

export type InflowWorkflow = (
  ctx: InflowContext,
) => Promise<FlowRunResult | void>;

export interface InflowConfig {
  /** Unique name for this flow (used for DB tracking and Hub display) */
  name: string;
  /** Logical resource this flow feeds, e.g. "products" */
  resource?: string;
  /** Optional cron schedule used by scheduler integrations */
  schedule?: string;
  /** Durable workflow that extracts, transforms, and loads records */
  workflow: InflowWorkflow;
}

export function inflow(config: InflowConfig): FlowRegistration {
  return {
    name: config.name,
    type: "inflow",
    resource: config.resource,
    schedule: config.schedule,
    workflow: config.workflow as FlowRegistration["workflow"],
  };
}

// ---------------------------------------------------------------------------
// Usage Example (create a file like flows/shopify-products.ts)
// ---------------------------------------------------------------------------
//
// Declare "use step" functions at MODULE TOP LEVEL and pass them serializable
// values only. The `ctx` object is plain data and is safe to pass. Do NOT nest
// step functions inside the "use workflow" function — the Workflow compiler
// cannot hoist closures that capture workflow scope, so they fail at runtime.
//
// import { bindWorkflowPlug, inflow, type InflowContext, sendUpdate } from "khotan-data/factory";
// import { db } from "@/db";
// import { products } from "@/db/schema";
// import { shopifyPlug } from "../plugs/shopify";
//
// // Step: top-level, full Node.js access, retried independently.
// async function extractAndLoad(ctx: InflowContext) {
//   "use step";
//   console.log("Starting inflow", {
//     flow: ctx.flow.name,
//     khotanRunId: ctx.khotanRunId,
//     runType: ctx.runType,
//   });
//   await sendUpdate({ message: "Starting Shopify products inflow" });
//   const shopify = bindWorkflowPlug(shopifyPlug, ctx);
//
//   const response = await shopify.get<{ data?: Array<{ id: string; sku?: string }> }>("/products");
//   const records = Array.isArray(response.data) ? response.data : [];
//   await sendUpdate({ message: `Fetched ${records.length} products`, extracted: records.length });
//
//   if (records.length > 0) {
//     await db.insert(products).values(
//       records.map((record) => ({
//         externalId: record.id,
//         sku: record.sku ?? record.id,
//       })),
//     );
//   }
//
//   return {
//     extracted: records.length,
//     transformed: records.length,
//     created: records.length,
//     metadata: { source: ctx.flow.name },
//   };
// }
//
// // Workflow: orchestration only.
// async function shopifyProductsWorkflow(ctx: InflowContext) {
//   "use workflow";
//   return extractAndLoad(ctx);
// }
//
// export const shopifyProductsInflow = inflow({
//   name: "shopify-products-inflow",
//   resource: "products",
//   schedule: "0 * * * *",
//   workflow: shopifyProductsWorkflow,
// });
