// ============================================================================
// Ingest — typed inbound destination endpoint builder
// Generated by khotan CLI · https://github.com/khotan-io/khotan-data
//
// This file re-exports the package-level ingest() builder and its public types.
// Create per-destination handlers next to it, then mount each handler from a
// Next.js App Router route.
//
// The builder intentionally does not ship a fake persistence layer. Wire
// idempotency and unresolved-intake parking to tables in your app database.
// ============================================================================

export {
  ingest,
  type IngestConfig,
  type IngestHeaders,
  type IngestIdempotencyClaim,
  type IngestIdempotencyStore,
  type IngestMappingHelper,
  type IngestMappingStore,
  type IngestRegistration,
  type IngestRequestContext,
  type IngestResolvedContext,
  type IngestResponse,
  type IngestSchema,
  type IngestUnresolvedContext,
  type InferIngestBody,
} from "khotan-data/factory";

// ---------------------------------------------------------------------------
// Usage shape
// ---------------------------------------------------------------------------
//
// import { z } from "zod";
// import { ingest } from "./ingest";
//
// const ProviderEvent = z.object({
//   eventId: z.string(),
//   orgKey: z.string(),
//   providerId: z.string(),
// });
//
// export const providerIngest = ingest({
//   name: "provider-events",
//   schema: ProviderEvent,
//   resolveOrg: async ({ body }) => {
//     // Look up your organization/tenant by body.orgKey or headers.
//     return { id: body.orgKey };
//   },
//   idempotencyKey: (body) => body.eventId,
//   idempotencyStore: {
//     async claim(key) {
//       // INSERT key into an ingest_idempotency table with a unique constraint.
//       // Return { status: "duplicate" } when the insert conflicts.
//       return { status: "claimed" };
//     },
//     async complete(key, result) {
//       // Store the result for future duplicate responses.
//     },
//   },
//   onUnresolved: async ({ body, idempotencyKey }) => {
//     // INSERT the full event into an unresolved_intake table for review/replay.
//     return { status: "parked", idempotencyKey, providerId: body.providerId };
//   },
//   handler: async (ctx, event) => {
//     await ctx
//       .mapping("resource-id")
//       .upsertProviderRef("provider", event.providerId, event.orgKey);
//     return { status: "processed" };
//   },
// });
//
// export const POST = providerIngest.POST;
