// ============================================================================
// Example ingest handler — replace with your destination/provider endpoint
// Generated by khotan CLI · https://github.com/khotan-io/khotan-data
// ============================================================================

import { z } from "zod";
import {
  ingest,
  type IngestIdempotencyStore,
  type IngestMappingStore,
} from "./ingest";

const PackiyoInventoryEvent = z.object({
  eventId: z.string().min(1),
  orgKey: z.string().min(1),
  sku: z.string().min(1),
  providerInventoryId: z.string().min(1),
  quantity: z.number().int(),
});

type PackiyoInventoryEvent = z.infer<typeof PackiyoInventoryEvent>;

interface OrgRef {
  id: string;
  key: string;
}

type IngestResult =
  | {
      status: "processed";
      sku: string;
      quantity: number;
    }
  | {
      status: "parked";
      reason: "org_not_found";
      orgKey: string;
      eventId?: string;
    };

const idempotencyStore: IngestIdempotencyStore<
  PackiyoInventoryEvent,
  OrgRef,
  IngestResult
> = {
  async claim(key) {
    // Implement with a durable unique constraint, for example:
    //
    // await db.insert(ingestIdempotency).values({ key, status: "claimed" });
    // return { status: "claimed" };
    //
    // On unique violation, read the existing row and return its saved result
    // and parked state:
    // return {
    //   status: "duplicate",
    //   result: existing.result as IngestResult | undefined,
    //   parked: existing.parked,
    // };
    //
    // Do not replace this with an in-memory Set in production; serverless
    // instances and retries will bypass it.
    throw new Error(`Configure durable ingest idempotency storage for ${key}`);
  },
  async complete(key, result, ctx) {
    // Persist result/status and ctx.parked for future duplicate responses.
    void key;
    void result;
    void ctx;
  },
  async fail(key, error) {
    // Mark the claimed key failed or retryable, depending on your policy.
    void key;
    void error;
  },
};

const mappings: IngestMappingStore = {
  async lookup(params) {
    // Use your khotanData.lookupMapping(...) helper or adapter-backed query.
    // params.resourceId can be a known resource row id or your own resolver's
    // output if you wrap this store.
    void params;
    return null;
  },
  async upsert(mapping) {
    // Example:
    // return khotanData.upsertMapping(mapping);
    void mapping;
    throw new Error("Configure khotan mapping upsert integration");
  },
};

async function resolveOrg(event: PackiyoInventoryEvent): Promise<OrgRef | null> {
  // Replace with your tenant lookup, for example:
  // const org = await db.query.organizations.findFirst({
  //   where: eq(organizations.packiyoOrgKey, event.orgKey),
  // });
  // return org ? { id: org.id, key: event.orgKey } : null;
  void event;
  return null;
}

export const packiyoInventoryIngest = ingest({
  name: "packiyo-inventory",
  schema: PackiyoInventoryEvent,
  resolveOrg: ({ body }) => resolveOrg(body),
  idempotencyKey: (body) => body.eventId,
  idempotencyStore,
  mappings,
  onUnresolved: async ({ body, idempotencyKey }) => {
    // Park the full payload in an unresolved_intake table with enough context
    // to replay it after the org/provider mapping is fixed:
    //
    // await db.insert(unresolvedIntake).values({
    //   source: "packiyo",
    //   resource: "inventory",
    //   reason: "org_not_found",
    //   orgKey: body.orgKey,
    //   idempotencyKey,
    //   payload: body,
    // });
    return {
      status: "parked",
      reason: "org_not_found",
      orgKey: body.orgKey,
      ...(idempotencyKey ? { eventId: idempotencyKey } : {}),
    };
  },
  handler: async (ctx, event) => {
    await ctx
      .mapping("products-resource-id")
      .upsertProviderRef("packiyo", event.providerInventoryId, event.sku, {
        orgId: ctx.org.id,
      });

    // Upsert your destination/app table here. Example:
    //
    // await db.insert(inventory).values({
    //   orgId: ctx.org.id,
    //   sku: event.sku,
    //   quantity: event.quantity,
    // }).onConflictDoUpdate({
    //   target: [inventory.orgId, inventory.sku],
    //   set: { quantity: event.quantity },
    // });

    return {
      status: "processed",
      sku: event.sku,
      quantity: event.quantity,
    };
  },
});
