// ============================================================================
// Example internal ingest route
// Generated by khotan CLI · https://github.com/khotan-io/khotan-data
//
// POST /api/internal/khotan/ingest/example
// ============================================================================

import { packiyoInventoryIngest } from "__KHOTAN_INGEST_IMPORT__";

export const runtime = "nodejs";
export const POST = packiyoInventoryIngest.POST;
