// ============================================================================
// Khotan API Route — catch-all handler for /api/khotan/*
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file wires your khotan config into a Next.js App Router route.
// ============================================================================

import { toNextJsHandler } from "khotan-data/factory";
import khotanData from "@/lib/khotan/khotan";

export const { GET, POST, PUT, DELETE } = toNextJsHandler(khotanData.handler);
