// ============================================================================
// Khotan Config — register your plugs, caches, and flows here
// Generated by khotan CLI · https://github.com/khotan-data
//
// Import your Drizzle database instance and register plugs below.
// Restart the dev server after making changes.
// ============================================================================

import { khotan, drizzleAdapter } from "khotan-data/factory";
// TODO: Update this import to your Drizzle database instance
import { db } from "@/db";

const khotanData = khotan({
  adapter: drizzleAdapter(db),

  // ── Security ──────────────────────────────────────────────────────────────
  // The management API (/api/khotan/*) and the Hub dashboard expose plug
  // credentials and operational controls. Gate every management route behind
  // your auth layer with `authorize`. It receives the raw Request, so it works
  // directly with session libraries like better-auth:
  //
  //   import { auth } from "@/lib/auth";
  //
  //   authorize: async (request) => {
  //     const session = await auth.api.getSession({ headers: request.headers });
  //     return Boolean(session?.user); // or: session?.user?.role === "admin"
  //   },
  //
  // Inbound webhooks, the cron dispatcher (CRON_SECRET), and debug routes are
  // exempt automatically. Without `authorize`, the API is PUBLIC.
  // authorize: async (request) => { /* return true to allow */ return false; },

  // Resources define logical entity types for cross-referencing across plugs.
  // The mapping block declares the shared identity contract for that resource.
  resources: [
    // Example resource registration:
    //
    // { name: "products", mapping: { connectField: "sku" }, description: "Product catalog" },
    // { name: "orders", mapping: { connectField: "order_number" } },
  ],

  plugs: [
    // Example plug registration:
    //
    // {
    //   name: "stripe",
    //   baseUrl: "https://api.stripe.com",
    //   authType: "bearer",
    //   flows: [
    //     { name: "products-inflow", type: "inflow", schedule: "0 * * * *", resource: "products" },
    //     { name: "invoices-inflow", type: "inflow", schedule: "0 0 * * *" },
    //   ],
    // },
  ],

  // Caches store durable key/value state for relays, inflows, outflows, and
  // webhook workflows. Register named caches you want to access via
  // khotanCache(ctx, "cache-name") or khotanData.cache("cache-name").
  caches: [
    // Example cache registration:
    //
    // cin7ProductsSnapshotCache,
  ],
});

export default khotanData;

// Trigger a flow run from server code (route handler, action, cron):
//
//   import khotanData from "@/lib/khotan/khotan";
//   await khotanData.flow("products-inflow", { plugName: "stripe" }).start({
//     runType: "delta", // or "full"
//   });
//
// `flow(name).start(options)` is the single entry point — there is no
// `khotanData.api.*` surface. `plugName` only disambiguates when the same flow
// name is registered under multiple plugs.
