// ============================================================================
// Khotan Config — register your plugs, caches, and flows here
// Generated by khotan CLI · https://github.com/khotan-data
//
// Import your Drizzle database instance and register plugs below.
// Restart the dev server after making changes.
// ============================================================================

import { khotan, drizzleAdapter } from "khotan-data/factory";
// Run `npx khotan add auth` to scaffold Better Auth and wire this hook:
// import { authorizeKhotanRequest } from "@/lib/auth";
// TODO: Update this import to your Drizzle database instance
import { db } from "@/db";

const khotanData = khotan({
  adapter: drizzleAdapter(db),

  // ── Security ──────────────────────────────────────────────────────────────
  // The management API (/api/khotan/*) and the Hub dashboard expose plug
  // credentials and operational controls. Gate every management route behind
  // your auth layer with `authorize`.
  //
  // Without `authorize`, development requests are rejected with 401 and
  // production startup throws. `authorize: false` explicitly opens the
  // management API for local development only and is rejected in production.
  //
  // To scaffold a Better Auth setup and wire this file automatically:
  //   npx khotan add auth
  //
  // Inbound webhooks, the cron dispatcher (CRON_SECRET), and debug routes are
  // exempt automatically.
  // authorize: authorizeKhotanRequest,

  // Resources define logical entity types for cross-referencing across plugs.
  // The mapping block declares the shared identity contract for that resource.
  resources: [
    // Example resource registration:
    //
    // { name: "products", mapping: { connectField: "sku" }, description: "Product catalog" },
    // { name: "orders", mapping: { connectField: "order_number" } },
  ],

  plugs: [
    // Example plug registration:
    //
    // import { stripePlug } from "./plugs/stripe";
    // import { stripeProductsInflow } from "./flows/stripe-products";
    //
    // {
    //   name: "stripe",
    //   plug: stripePlug,
    //   flows: [stripeProductsInflow],
    // },
  ],

  // Caches store durable key/value state for relays, inflows, outflows, and
  // webhook workflows. Register named caches you want to access via
  // khotanCache(ctx, "cache-name") or khotanData.cache("cache-name").
  caches: [
    // Example cache registration:
    //
    // cin7ProductsSnapshotCache,
  ],
});

export default khotanData;

// Trigger a flow run from server code (route handler, action, cron):
//
//   import khotanData from "@/lib/khotan/khotan";
//   await khotanData.flow("products-inflow", { plugName: "stripe" }).start({
//     variant: "delta", // the variant (run mode); defaults to "default"
//   });
//
// `flow(name).start(options)` is the single entry point — there is no
// `khotanData.api.*` surface. `plugName` only disambiguates when the same flow
// name is registered under multiple plugs.
