// ============================================================================
// Khotan Config — register your plugs, caches, and flows here
// Generated by khotan CLI · https://github.com/khotan-data
//
// Import your Drizzle database instance and register plugs below.
// Restart the dev server after making changes.
// ============================================================================

import { khotan, drizzleAdapter } from "khotan-data/factory";
// TODO: Update this import to your Drizzle database instance
import { db } from "@/db";

const khotanData = khotan({
  adapter: drizzleAdapter(db),

  // Resources define logical entity types for cross-referencing across plugs.
  // The mapping block declares the shared identity contract for that resource.
  resources: [
    // Example resource registration:
    //
    // { name: "products", mapping: { connectField: "sku" }, description: "Product catalog" },
    // { name: "orders", mapping: { connectField: "order_number" } },
  ],

  plugs: [
    // Example plug registration:
    //
    // {
    //   name: "stripe",
    //   baseUrl: "https://api.stripe.com",
    //   authType: "bearer",
    //   flows: [
    //     { name: "products-inflow", type: "inflow", schedule: "0 * * * *", resource: "products" },
    //     { name: "invoices-inflow", type: "inflow", schedule: "0 0 * * *" },
    //   ],
    // },
  ],

  // Caches store durable key/value state for relays, inflows, outflows, and
  // webhook workflows. Register named caches you want to access via
  // khotanCache(ctx, "cache-name") or khotanData.cache("cache-name").
  caches: [
    // Example cache registration:
    //
    // cin7ProductsSnapshotCache,
  ],
});

export default khotanData;
