// ============================================================================
// Example: Outflow
// Generated by khotan CLI · https://github.com/khotan-data
//
// Copy this file, rename it for your destination service/resource, and register
// the exported flow in {outputDir}/khotan.ts.
// ============================================================================

import { db } from "@/db";
import { products } from "@/db/schema";
import { hubspotPlug } from "../plugs/hubspot";
import { outflow, type OutflowContext } from "./outflow";

async function hubspotProductsWorkflow(ctx: OutflowContext) {
  "use workflow";

  async function loadAndPush() {
    "use step";
    console.log("Starting outflow", {
      flow: ctx.flow.name,
      khotanRunId: ctx.khotanRunId,
      runType: ctx.runType,
    });

    const records = await db.select().from(products);

    for (const record of records) {
      await hubspotPlug.post("/products", {
        vars: ctx.vars,
        body: record,
      });
    }

    return {
      extracted: records.length,
      transformed: records.length,
      created: records.length,
      metadata: { destination: ctx.flow.name },
    };
  }

  return loadAndPush();
}

export const hubspotProductsOutflow = outflow({
  name: "hubspot-products-outflow",
  resource: "products",
  schedule: "0 * * * *",
  workflow: hubspotProductsWorkflow,
});
