// ============================================================================
// Example: Outflow
// Generated by khotan CLI · https://github.com/khotan-data
//
// Copy this file, rename it for your destination service/resource, and register
// the exported flow in {outputDir}/khotan.ts.
// ============================================================================

import { outflow, type OutflowContext } from "./outflow";

async function hubspotProductsWorkflow(ctx: OutflowContext) {
  "use workflow";

  async function loadAndPush() {
    "use step";
    console.log("Starting outflow", {
      flow: ctx.flow.name,
      khotanRunId: ctx.khotanRunId,
      runType: ctx.runType,
    });

    // Replace this with your app-specific DB query.
    const records: Array<Record<string, unknown>> = [];

    for (const record of records) {
      await fetch("https://api.example.com/products", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${ctx.vars["apiToken"] ?? ""}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(record),
      });
    }

    return {
      extracted: records.length,
      transformed: records.length,
      created: records.length,
      metadata: { destination: ctx.flow.name },
    };
  }

  return loadAndPush();
}

export const hubspotProductsOutflow = outflow({
  name: "hubspot-products-outflow",
  resource: "products",
  schedule: "0 * * * *",
  workflow: hubspotProductsWorkflow,
});
