// ============================================================================
// Outflow — durable app → external service data movement
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file defines the outflow() builder and types. Create per-service flow
// files (e.g. crm-audiences.ts) using this builder to read app data and push it
// to an external service with durable, retryable Vercel Workflow steps.
// ============================================================================

import type {
  FlowRegistration,
  FlowRunResult,
  FlowWorkflowContext,
} from "khotan-data/factory";

export type OutflowContext = FlowWorkflowContext & {
  flow: FlowWorkflowContext["flow"] & { type: "outflow" };
};

export type OutflowWorkflow = (
  ctx: OutflowContext,
) => Promise<FlowRunResult | void>;

export interface OutflowConfig {
  /** Unique name for this flow (used for DB tracking and Hub display) */
  name: string;
  /** Logical resource this flow publishes, e.g. "products" */
  resource?: string;
  /** Optional cron schedule used by scheduler integrations */
  schedule?: string;
  /** Durable workflow that reads app data and writes it to the plug */
  workflow: OutflowWorkflow;
}

export function outflow(config: OutflowConfig): FlowRegistration {
  return {
    name: config.name,
    type: "outflow",
    resource: config.resource,
    schedule: config.schedule,
    workflow: config.workflow as FlowRegistration["workflow"],
  };
}

// ---------------------------------------------------------------------------
// Usage Example (create a file like flows/hubspot-products.ts)
// ---------------------------------------------------------------------------
//
// import { outflow, type OutflowContext } from "./outflow";
// import { db } from "@/db";
// import { products } from "@/db/schema";
// import { hubspotPlug } from "../plugs/hubspot";
//
// async function hubspotProductsWorkflow(ctx: OutflowContext) {
//   "use workflow";
//
//   async function loadAndPush() {
//     "use step";
//     console.log("Starting outflow", {
//       flow: ctx.flow.name,
//       khotanRunId: ctx.khotanRunId,
//       runType: ctx.runType,
//     });
//
//     const records = await db.select().from(products);
//
//     for (const record of records) {
//       await hubspotPlug.post("/products", {
//         vars: ctx.vars,
//         body: record,
//       });
//     }
//
//     return {
//       extracted: records.length,
//       transformed: records.length,
//       created: records.length,
//       metadata: { destination: ctx.flow.name },
//     };
//   }
//
//   return loadAndPush();
// }
//
// export const hubspotProductsOutflow = outflow({
//   name: "hubspot-products-outflow",
//   resource: "products",
//   schedule: "0 * * * *",
//   workflow: hubspotProductsWorkflow,
// });
