// ============================================================================
// Outflow — durable app → external service data movement
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file defines the outflow() builder and types. Create per-service flow
// files (e.g. crm-audiences.ts) using this builder to read app data and push it
// to an external service with durable, retryable Vercel Workflow steps.
// Outflow workflows can also use khotanCache(ctx, "name") for checkpoints, cursor
// state, or dedupe markers between runs.
// ============================================================================

import type {
  FlowRegistration,
  FlowRunResult,
  FlowVariant,
  FlowWorkflowContext,
} from "khotan-data/factory";

export type OutflowContext = FlowWorkflowContext & {
  flow: FlowWorkflowContext["flow"] & { type: "outflow" };
};

export type OutflowWorkflow = (
  ctx: OutflowContext,
) => Promise<FlowRunResult | void>;

export interface OutflowConfig {
  /** Unique name for this flow (used for DB tracking and Hub display) */
  name: string;
  /** Logical resource this flow publishes, e.g. "products" */
  resource?: string;
  /** Optional cron schedule. Mutually exclusive with `variants`. */
  schedule?: string;
  /**
   * Named run modes. Each variant may carry its own `schedule` and
   * `onError`/`onComplete` hooks. Flow code branches on `ctx.variant`.
   * Omit to get a single implicit `default` variant (using `schedule`).
   */
  variants?: Record<string, FlowVariant>;
  /** Durable workflow that reads app data and writes it to the plug */
  workflow: OutflowWorkflow;
}

export function outflow(config: OutflowConfig): FlowRegistration {
  return {
    name: config.name,
    type: "outflow",
    resource: config.resource,
    ...(config.variants
      ? { variants: config.variants }
      : { schedule: config.schedule }),
    workflow: config.workflow as FlowRegistration["workflow"],
  };
}

// ---------------------------------------------------------------------------
// Usage Example (create a file like flows/hubspot-products.ts)
// ---------------------------------------------------------------------------
//
// Declare "use step" functions at MODULE TOP LEVEL and pass them serializable
// values only (`ctx` is plain data). Do NOT nest steps inside the "use workflow"
// function — closures over workflow scope cannot be hoisted and fail at runtime.
//
// import { bindWorkflowPlug, outflow, type OutflowContext } from "khotan-data/factory";
// import { db } from "@/db";
// import { products } from "@/db/schema";
// import { hubspotPlug } from "../plugs/hubspot";
//
// // Step: top-level, full Node.js access, retried independently.
// async function loadAndPush(ctx: OutflowContext) {
//   "use step";
//   console.log("Starting outflow", {
//     flow: ctx.flow.name,
//     khotanRunId: ctx.khotanRunId,
//     variant: ctx.variant,
//   });
//   const hubspot = bindWorkflowPlug(hubspotPlug, ctx);
//
//   const records = await db.select().from(products);
//
//   await hubspot.batchPost("/products", records, {
//     batchSize: 200,
//     concurrency: 2,
//   });
//
//   return {
//     extracted: records.length,
//     transformed: records.length,
//     created: records.length,
//     metadata: { destination: ctx.flow.name },
//   };
// }
//
// // Workflow: orchestration only.
// async function hubspotProductsWorkflow(ctx: OutflowContext) {
//   "use workflow";
//   return loadAndPush(ctx);
// }
//
// export const hubspotProductsOutflow = outflow({
//   name: "hubspot-products-outflow",
//   resource: "products",
//   schedule: "0 * * * *",
//   workflow: hubspotProductsWorkflow,
// });
