// ============================================================================
// Outflow — durable app → external service data movement
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file keeps local imports stable while reusing the real builder and types
// from khotan-data/factory. Create per-service flow files using outflow() to
// read app data and push it to an external service with durable, retryable
// Vercel Workflow steps.
// ============================================================================

export { outflow } from "khotan-data/factory";

export type {
  FlowRegistration,
  FlowRunResult,
  FlowVariant,
  OutflowConfig,
  OutflowContext,
  OutflowWorkflow,
} from "khotan-data/factory";

// ---------------------------------------------------------------------------
// Usage Example (create a file like flows/hubspot-products.ts)
// ---------------------------------------------------------------------------
//
// Declare "use step" functions at MODULE TOP LEVEL and pass them serializable
// values only (`ctx` is plain data). Do NOT nest steps inside the "use workflow"
// function — closures over workflow scope cannot be hoisted and fail at runtime.
//
// import { bindWorkflowPlug, outflow, type OutflowContext } from "khotan-data/factory";
// import { db } from "@/db";
// import { products } from "@/db/schema";
// import { hubspotPlug } from "../plugs/hubspot";
//
// // Step: top-level, full Node.js access, retried independently.
// async function loadAndPush(ctx: OutflowContext) {
//   "use step";
//   console.log("Starting outflow", {
//     flow: ctx.flow.name,
//     khotanRunId: ctx.khotanRunId,
//     variant: ctx.variant,
//   });
//   const hubspot = bindWorkflowPlug(hubspotPlug, ctx);
//
//   const records = await db.select().from(products);
//
//   for (const record of records) {
//     await hubspot.post("/products", { body: record });
//   }
//
//   return {
//     extracted: records.length,
//     transformed: records.length,
//     created: records.length,
//     metadata: { destination: ctx.flow.name },
//   };
// }
//
// // Workflow: orchestration only.
// async function hubspotProductsWorkflow(ctx: OutflowContext) {
//   "use workflow";
//   return loadAndPush(ctx);
// }
//
// export const hubspotProductsOutflow = outflow({
//   name: "hubspot-products-outflow",
//   resource: "products",
//   schedule: "0 * * * *",
//   workflow: hubspotProductsWorkflow,
// });
