// ============================================================================
// Example: Pass
// Generated by khotan CLI · https://github.com/khotan-data
//
// Copy this file, rename it for your source/destination pair, and register the
// exported pass handler in {outputDir}/khotan.ts.
// ============================================================================

import { plug, bearer } from "../plugs/plug";
import { pass, type PassContext } from "./pass";

async function stripeToSlackWorkflow(ctx: PassContext) {
  "use workflow";

  async function forwardEvent() {
    "use step";
    console.log("Forwarding webhook event", {
      eventType: ctx.eventType,
      khotanRunId: ctx.khotanRunId,
    });

    const slackPlug = plug({
      baseUrl: "https://slack.com/api",
      auth: bearer(ctx.destVars["botToken"] ?? ""),
    });

    await slackPlug.post("/chat.postMessage", {
      body: {
        channel: ctx.destVars["channelId"],
        text: `Received ${ctx.eventType}`,
        blocks: [
          {
            type: "section",
            text: {
              type: "mrkdwn",
              text: `Received ${ctx.eventType} from Stripe`,
            },
          },
        ],
      },
    });
  }

  await forwardEvent();
}

export const stripeToSlack = pass({
  name: "stripe-to-slack",
  to: "slack",
  events: ["invoice.paid"],
  workflow: stripeToSlackWorkflow,
});
