// ============================================================================
// Pass — durable webhook event forwarding via Vercel Workflow
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file defines the pass() builder and types. Create per-service pass
// files (e.g. pollinate-to-slack.ts) using this builder to forward verified
// webhook events to another service with durable, retryable workflow steps.
//
// Pass workflows receive a PassContext with the parsed event, event type,
// headers, and destVars (variables for the destination plug). Steps have
// full Node.js access — construct destination plugs from destVars.
// ============================================================================

// ---------------------------------------------------------------------------
// Context — serializable data passed to the workflow
// ---------------------------------------------------------------------------

export interface PassContext {
  /** Parsed webhook payload */
  event: Record<string, unknown>;
  /** Event type extracted from payload (e.g. "order.created") */
  eventType: string;
  /** Incoming request headers */
  headers: Record<string, string>;
  /** Decrypted variables for the destination plug (auto-injected by factory) */
  destVars: Record<string, string>;
  /** Khotan run ID created for this webhook handler execution */
  khotanRunId: string;
  /** Internal Khotan instance identifier for helper APIs */
  khotanInstanceId: string;
}

// ---------------------------------------------------------------------------
// Workflow type — the function signature your workflow must conform to
// ---------------------------------------------------------------------------

export type PassWorkflow = (ctx: PassContext) => Promise<void>;

// ---------------------------------------------------------------------------
// Config — passed to the pass() builder
// ---------------------------------------------------------------------------

export interface PassConfig {
  /** Unique name for this pass handler (used for DB tracking and Hub display) */
  name: string;
  /** Name of the destination plug to forward events to */
  to: string;
  /** Event types this pass should receive */
  events?: string[];
  /** Workflow function that handles the forwarding */
  workflow: PassWorkflow;
}

// ---------------------------------------------------------------------------
// Registration — returned by pass(), consumed by factory config
// ---------------------------------------------------------------------------

export interface PassRegistration {
  type: "pass";
  name: string;
  to: string;
  events?: string[];
  workflow: PassWorkflow;
}

// ---------------------------------------------------------------------------
// Builder
// ---------------------------------------------------------------------------

export function pass(config: PassConfig): PassRegistration {
  return {
    type: "pass",
    name: config.name,
    to: config.to,
    events: config.events,
    workflow: config.workflow,
  };
}

// ---------------------------------------------------------------------------
// Usage Example (create a file like webhooks/pollinate-to-slack.ts)
// ---------------------------------------------------------------------------
//
// import { khotanCache } from "khotan-data/factory";
// import { pass, type PassContext } from "./pass";
// import { plug } from "../plugs/plug";
//
// Declare "use step" functions at MODULE TOP LEVEL and pass them serializable
// values only (`ctx` is plain data). Do NOT nest steps inside the "use workflow"
// function — closures over workflow scope cannot be hoisted and fail at runtime.
//
// // Step: top-level, full Node.js access, retried independently.
// async function forwardEvent(ctx: PassContext) {
//   "use step";
//   const cache = khotanCache(ctx, "pollinate-forwarded-events");
//   const eventId = String(ctx.event["id"] ?? "");
//   if (eventId && (await cache.get<boolean>(eventId))) return;
//
//   // Construct destination plug from destVars
//   const slackPlug = plug({
//     name: "slack",
//     baseUrl: "https://hooks.slack.com",
//     authType: "bearer",
//     auth: { bearer: { token: ctx.destVars["token"] ?? "" } },
//   });
//
//   await slackPlug.post("/services/webhook", {
//     body: {
//       text: `Received ${ctx.eventType} event from pollinate`,
//       event: ctx.event,
//     },
//   });
//
//   if (eventId) {
//     await cache.set(eventId, true);
//   }
// }
//
// // Workflow: orchestration only.
// async function pollinateToSlackWorkflow(ctx: PassContext) {
//   "use workflow";
//   await forwardEvent(ctx);
// }
//
// export const pollinateToSlack = pass({
//   name: "pollinate-to-slack",
//   to: "slack",
//   events: ["order.created"],
//   workflow: pollinateToSlackWorkflow,
// });
//
// Then register in your khotan config:
//
// plugs: [{
//   name: "pollinate",
//   plug: pollinatePlug,
//   wires: [pollinateWire],
//   passes: [pollinateToSlack],
// }]
