"use client";

import { useEffect, useState, useCallback } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

// ============================================================================
// Plug Debugger — Dev-only panel for testing plug requests interactively
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file is yours. Restyle, extend, or embed it however you like.
// It uses shadcn/ui primitives and fetches from /api/khotan/debug.
// Gated behind KHOTAN_DEBUG env var — hidden in production.
// ============================================================================

interface Endpoint {
  name: string;
  method: string;
  path: string;
}

interface DebugResponse {
  status: number;
  statusText: string;
  headers: Record<string, string>;
  body: unknown;
  timing: number;
  endpoint?: { name: string; method: string; path: string };
  error?: string;
}

interface PlugDebuggerProps {
  plugName: string;
  endpoints?: Record<string, { method: string; path: string }>;
  basePath?: string;
}

const METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE"] as const;

export function PlugDebugger({
  plugName,
  endpoints,
  basePath = "/api/khotan",
}: PlugDebuggerProps) {
  const [available, setAvailable] = useState<boolean | null>(null);
  const [method, setMethod] = useState<string>("GET");
  const [path, setPath] = useState("");
  const [body, setBody] = useState("");
  const [params, setParams] = useState("");
  const [headers, setHeaders] = useState("");
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState<DebugResponse | null>(null);
  const [showHeaders, setShowHeaders] = useState(false);

  const checkAvailability = useCallback(async () => {
    try {
      const res = await fetch(`${basePath}/debug/${plugName}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ method: "GET", path: "/" }),
      });
      setAvailable(res.status !== 404);
    } catch {
      setAvailable(false);
    }
  }, [basePath, plugName]);

  useEffect(() => {
    checkAvailability();
  }, [checkAvailability]);

  if (available === null || available === false) return null;

  const endpointList: Endpoint[] = endpoints
    ? Object.entries(endpoints).map(([name, ep]) => ({
        name,
        method: ep.method,
        path: ep.path,
      }))
    : [];

  function selectEndpoint(name: string) {
    const ep = endpointList.find((e) => e.name === name);
    if (ep) {
      setMethod(ep.method.toUpperCase());
      setPath(ep.path);
    }
  }

  async function fireRequest() {
    setLoading(true);
    setResponse(null);
    try {
      const payload: Record<string, unknown> = { method, path };

      if (body.trim()) {
        try {
          payload.body = JSON.parse(body);
        } catch {
          payload.body = body;
        }
      }

      if (params.trim()) {
        try {
          payload.params = JSON.parse(params);
        } catch {
          /* ignore invalid params */
        }
      }

      if (headers.trim()) {
        try {
          payload.headers = JSON.parse(headers);
        } catch {
          /* ignore invalid headers */
        }
      }

      const res = await fetch(`${basePath}/debug/${plugName}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      const data = await res.json();
      setResponse(data);
    } catch (err) {
      setResponse({
        status: 0,
        statusText: "Network Error",
        headers: {},
        body: null,
        timing: 0,
        error: err instanceof Error ? err.message : "Unknown error",
      });
    } finally {
      setLoading(false);
    }
  }

  const statusColor =
    response && response.status >= 200 && response.status < 300
      ? "default"
      : response && response.status >= 400
        ? "destructive"
        : "secondary";

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-sm font-medium flex items-center gap-2">
          Debug: {plugName}
          <Badge variant="outline" className="text-[10px]">
            DEV
          </Badge>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {endpointList.length > 0 && (
          <div className="space-y-1">
            <Label className="text-xs">Typed Endpoints</Label>
            <select
              className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
              onChange={(e) => {
                if (e.target.value) selectEndpoint(e.target.value);
              }}
              defaultValue=""
            >
              <option value="">Select an endpoint...</option>
              {endpointList.map((ep) => (
                <option key={ep.name} value={ep.name}>
                  {ep.method.toUpperCase()} {ep.path} — {ep.name}
                </option>
              ))}
            </select>
          </div>
        )}

        <div className="flex gap-2">
          <div className="w-28">
            <Label className="text-xs">Method</Label>
            <select
              className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
              value={method}
              onChange={(e) => setMethod(e.target.value)}
            >
              {METHODS.map((m) => (
                <option key={m} value={m}>
                  {m}
                </option>
              ))}
            </select>
          </div>
          <div className="flex-1">
            <Label className="text-xs">Path</Label>
            <Input
              placeholder="/products"
              value={path}
              onChange={(e) => setPath(e.target.value)}
            />
          </div>
        </div>

        {(method === "POST" || method === "PUT" || method === "PATCH") && (
          <div className="space-y-1">
            <Label className="text-xs">Body (JSON)</Label>
            <textarea
              className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm font-mono min-h-[80px] resize-y"
              placeholder='{ "key": "value" }'
              value={body}
              onChange={(e) => setBody(e.target.value)}
            />
          </div>
        )}

        <div className="space-y-1">
          <Label className="text-xs">Query Params (JSON)</Label>
          <Input
            placeholder='{ "limit": "10" }'
            value={params}
            onChange={(e) => setParams(e.target.value)}
            className="font-mono text-xs"
          />
        </div>

        <div className="space-y-1">
          <Label className="text-xs">Extra Headers (JSON)</Label>
          <Input
            placeholder='{ "X-Custom": "value" }'
            value={headers}
            onChange={(e) => setHeaders(e.target.value)}
            className="font-mono text-xs"
          />
        </div>

        <Button onClick={fireRequest} disabled={loading || !path} size="sm">
          {loading ? "Sending..." : "Send Request"}
        </Button>

        {response && (
          <div className="space-y-3 border-t pt-3">
            <div className="flex items-center gap-3">
              <Badge variant={statusColor}>{response.status}</Badge>
              <span className="text-xs text-muted-foreground">
                {response.statusText}
              </span>
              <span className="text-xs text-muted-foreground ml-auto">
                {response.timing}ms
              </span>
            </div>

            {response.error && (
              <p className="text-xs text-destructive">{response.error}</p>
            )}

            {response.endpoint && (
              <div className="text-xs text-muted-foreground">
                Matched endpoint:{" "}
                <code className="bg-muted px-1 py-0.5 rounded">
                  {response.endpoint.name}
                </code>
              </div>
            )}

            {response.headers &&
              Object.keys(response.headers).length > 0 && (
                <div>
                  <button
                    className="text-xs text-muted-foreground underline hover:no-underline"
                    onClick={() => setShowHeaders(!showHeaders)}
                  >
                    {showHeaders ? "Hide" : "Show"} Headers (
                    {Object.keys(response.headers).length})
                  </button>
                  {showHeaders && (
                    <pre className="mt-1 text-[11px] bg-muted rounded p-2 overflow-x-auto max-h-32">
                      {JSON.stringify(response.headers, null, 2)}
                    </pre>
                  )}
                </div>
              )}

            <div className="space-y-1">
              <span className="text-xs font-medium">Response Body</span>
              <pre className="text-[11px] bg-muted rounded p-2 overflow-x-auto max-h-64">
                {typeof response.body === "string"
                  ? response.body
                  : JSON.stringify(response.body, null, 2)}
              </pre>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
