// ============================================================================
// Example: Typed Endpoints with defineContract + Plug
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file demonstrates how to define a typed API contract and create a
// type-safe client using createPlugClient. Delete or rename it as needed.
// ============================================================================

import { z } from "zod";
import { defineContract, createPlugClient } from "khotan-data/plug";
import { plug, bearer } from "./plug";

// ---------------------------------------------------------------------------
// 1. Define your API contract
// ---------------------------------------------------------------------------

const ProductSchema = z.object({
  id: z.string(),
  name: z.string(),
  price: z.number(),
  createdAt: z.string(),
});

const ErrorSchema = z.object({
  error: z.string(),
  message: z.string(),
});

export const apiContract = defineContract({
  listProducts: {
    method: "GET",
    path: "/products",
    query: z.object({
      page: z.number().optional(),
      limit: z.number().optional(),
    }),
    responses: {
      200: z.object({
        data: z.array(ProductSchema),
        total: z.number(),
      }),
    },
  },
  getProduct: {
    method: "GET",
    path: "/products/:id",
    responses: {
      200: ProductSchema,
      404: ErrorSchema,
    },
  },
  createProduct: {
    method: "POST",
    path: "/products",
    body: z.object({
      name: z.string(),
      price: z.number(),
    }),
    responses: {
      201: ProductSchema,
      400: ErrorSchema,
    },
  },
});

// ---------------------------------------------------------------------------
// 2. Create a typed client from contract + Plug instance
// ---------------------------------------------------------------------------

const api = plug({
  baseUrl: "https://api.example.com",
  auth: bearer(process.env.API_TOKEN!),
});

export const client = createPlugClient(apiContract, api);

// ---------------------------------------------------------------------------
// 3. Usage — fully typed, validated, with IDE autocomplete
// ---------------------------------------------------------------------------

// GET /products?page=1&limit=10
// const products = await client.listProducts({ query: { page: 1, limit: 10 } });
// products.body.data — typed as { id, name, price, createdAt }[]

// GET /products/:id
// const product = await client.getProduct({ params: { id: "abc" } });
// if (product.status === 200) product.body.name — typed as string
// if (product.status === 404) product.body.error — typed as string

// POST /products
// const created = await client.createProduct({
//   body: { name: "Widget", price: 9.99 },
// });
