// ============================================================================
// Plug — a self-contained fetch wrapper for external APIs
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file is yours. Edit anything — auth strategies, retry logic,
// pagination helpers, error handling. It has zero runtime dependencies
// on khotan-data.
// ============================================================================

// ---------------------------------------------------------------------------
// Debug logger — set KHOTAN_DEBUG=1 to see trace output
// ---------------------------------------------------------------------------

const _khotanDebug = (
  globalThis as { process?: { env?: Record<string, string | undefined> } }
).process?.env?.["KHOTAN_DEBUG"];
function kd(scope: string, ...args: unknown[]) {
  if (_khotanDebug) console.log(`[khotan:${scope}]`, ...args);
}

// ---------------------------------------------------------------------------
// Error
// ---------------------------------------------------------------------------

export class PlugError extends Error {
  constructor(
    message: string,
    public readonly status: number,
    public readonly statusText: string,
    public readonly body: unknown,
    public readonly url: string,
    public readonly method: string,
  ) {
    super(message);
    this.name = "PlugError";
  }
}

// ---------------------------------------------------------------------------
// Auth strategies
// ---------------------------------------------------------------------------

export interface QueryParamAuth {
  name: string;
  value: string;
}

export interface AuthStrategy {
  type: string;
  /** Mutate the outgoing request headers. Receives the plug's bound vars
   *  (decrypted plug variables for this run) so a custom strategy can read
   *  credentials without reaching back into the factory. The optional context
   *  exposes the fully resolved request URL for auth schemes that sign the
   *  method, query string, or body. */
  apply(
    headers: Headers,
    vars?: Record<string, string>,
    context?: AuthApplyContext,
  ): void | Promise<void>;
  onUnauthorized?: (
    vars?: Record<string, string>,
    context?: AuthApplyContext,
  ) => void | Promise<void>;
  baseUrl?: string;
  queryParam?: QueryParamAuth;
}

export interface AuthApplyContext<Vars = Record<string, string>> {
  url: string;
  query: string;
  searchParams: URLSearchParams;
  method: string;
  body?: unknown;
  vars: Vars;
}

export function bearer(
  token: string | (() => string | Promise<string>),
): AuthStrategy {
  return {
    type: "bearer",
    async apply(headers: Headers) {
      const t = typeof token === "function" ? await token() : token;
      headers.set("Authorization", `Bearer ${t}`);
    },
  };
}

export function basic(username: string, password: string): AuthStrategy {
  return {
    type: "basic",
    apply(headers: Headers) {
      const encoded = btoa(`${username}:${password}`);
      headers.set("Authorization", `Basic ${encoded}`);
    },
  };
}

export function apiKey(
  name: string,
  value: string,
  options?: { in?: "header" | "query" },
): AuthStrategy {
  const location = options?.in ?? "header";
  return {
    type: "apiKey",
    apply(headers: Headers) {
      if (location === "header") {
        headers.set(name, value);
      }
    },
    ...(location === "query" ? { queryParam: { name, value } } : {}),
  };
}

export function custom(
  fn: (
    headers: Headers,
    vars?: Record<string, string>,
    context?: AuthApplyContext,
  ) => void | Promise<void>,
): AuthStrategy {
  return {
    type: "custom",
    apply: fn,
  };
}

export interface HmacSignatureConfig {
  /**
   * Label for documentation/debugging. The sign function owns the actual
   * signing implementation so this template stays dependency-free.
   */
  algorithm?: "sha1" | "sha256" | "sha384" | "sha512";
  /** Header that receives the computed signature. Defaults to X-Signature. */
  header?: string;
  sign: (
    context: AuthApplyContext<Record<string, string>>,
  ) => string | Promise<string>;
}

export function hmacSignature(config: HmacSignatureConfig): AuthStrategy {
  return {
    type: "hmacSignature",
    async apply(headers, vars, context) {
      if (!context) {
        throw new Error("hmacSignature requires request context");
      }
      const signature = await config.sign({
        ...context,
        vars: vars ?? context.vars,
      });
      headers.set(config.header ?? "X-Signature", signature);
    },
  };
}

// ---------------------------------------------------------------------------
// Var fields — declare what runtime variables a plug needs
// ---------------------------------------------------------------------------

export interface VarField {
  readonly key: string;
  label: string;
  type: "text" | "password" | "url";
  secret?: boolean;
  hidden?: boolean;
  required?: boolean;
  placeholder?: string;
  defaultValue?: string;
}

// ---------------------------------------------------------------------------
// Type utilities for inferring var keys
// ---------------------------------------------------------------------------

type VarKeys<V extends readonly VarField[]> = V[number]["key"];
type VarsRecord<V extends readonly VarField[]> = Record<VarKeys<V>, string>;

// ---------------------------------------------------------------------------
// Token exchange auth strategy
// ---------------------------------------------------------------------------

export interface TokenExchangeConfig {
  getVariables: () => Promise<Record<string, string>> | Record<string, string>;
  /** Full URL or path relative to the plug's baseUrl (e.g. "/token") */
  tokenEndpoint: string;
  buildTokenRequest: (vars: Record<string, string>) => {
    headers?: Record<string, string>;
    /**
     * Request body. A plain object is JSON-encoded with a default
     * `Content-Type: application/json`. A `string` or `URLSearchParams` is sent
     * verbatim and the `Content-Type` you set in `headers` is honored — use this
     * for OAuth2 endpoints that require `application/x-www-form-urlencoded`, e.g.
     * `body: new URLSearchParams({ grant_type: "client_credentials" })`.
     */
    body?: unknown;
    method?: string;
  };
  parseTokenResponse: (data: unknown) => {
    accessToken: string;
    expiresIn?: number;
    expiresAt?: number;
    refreshToken?: string;
    tokenType?: string;
  };
  extraHeaders?: (vars: Record<string, string>) => Record<string, string>;
  refreshBufferSeconds?: number;
  tokenStore?: TokenStore;
}

export interface StoredAuthToken {
  accessToken: string;
  expiresAt?: number;
  refreshToken?: string;
  tokenType?: string;
}

export interface TokenStore {
  get(): StoredAuthToken | null | Promise<StoredAuthToken | null>;
  set(token: StoredAuthToken): void | Promise<void>;
  clear?(): void | Promise<void>;
}

export function tokenExchange(config: TokenExchangeConfig): AuthStrategy {
  let cachedToken: string | null = null;
  let tokenExpiresAt = 0;
  let _baseUrl = "";
  const refreshBuffer = (config.refreshBufferSeconds ?? 60) * 1000;

  function resolveEndpoint(): string {
    const ep = config.tokenEndpoint;
    if (ep.startsWith("http://") || ep.startsWith("https://")) return ep;
    return `${_baseUrl.replace(/\/$/, "")}${ep.startsWith("/") ? "" : "/"}${ep}`;
  }

  function isExpired(): boolean {
    if (!cachedToken) return true;
    if (tokenExpiresAt === 0) return false;
    return Date.now() >= tokenExpiresAt - refreshBuffer;
  }

  function cacheToken(token: StoredAuthToken) {
    cachedToken = token.accessToken;
    tokenExpiresAt = token.expiresAt ?? 0;
  }

  async function loadStoredToken(): Promise<boolean> {
    if (!config.tokenStore) return false;
    const stored = await config.tokenStore.get();
    if (!stored?.accessToken) return false;
    cacheToken(stored);
    kd("auth", "tokenExchange: loaded token from tokenStore");
    return !isExpired();
  }

  async function clearToken() {
    cachedToken = null;
    tokenExpiresAt = 0;
    await config.tokenStore?.clear?.();
  }

  async function fetchToken(): Promise<string> {
    const vars = await config.getVariables();
    kd(
      "auth",
      "tokenExchange: fetching token, has variables:",
      Object.keys(vars).join(", "),
    );
    const reqConfig = config.buildTokenRequest(vars);

    const headers = new Headers(reqConfig.headers);
    // Send a pre-encoded body (string / URLSearchParams) verbatim and honor the
    // caller's Content-Type; only JSON-encode plain objects (and default the
    // Content-Type for them). This lets token endpoints that require
    // application/x-www-form-urlencoded work without a custom AuthStrategy.
    let tokenBody: BodyInit | undefined;
    if (reqConfig.body == null) {
      tokenBody = undefined;
    } else if (
      typeof reqConfig.body === "string" ||
      reqConfig.body instanceof URLSearchParams
    ) {
      tokenBody = reqConfig.body;
    } else {
      tokenBody = JSON.stringify(reqConfig.body);
      if (!headers.has("Content-Type")) {
        headers.set("Content-Type", "application/json");
      }
    }

    const endpoint = resolveEndpoint();
    kd("auth", "tokenExchange: POST", endpoint);
    const init: RequestInit = {
      method: reqConfig.method ?? "POST",
      headers,
    };
    if (tokenBody !== undefined) {
      init.body = tokenBody;
    }
    const res = await fetch(endpoint, init);

    if (!res.ok) {
      const body = await res.text().catch(() => "");
      kd("auth", "tokenExchange: FAILED", res.status, res.statusText, body);
      throw new PlugError(
        `Token exchange failed: ${res.status} ${res.statusText}`,
        res.status,
        res.statusText,
        body,
        endpoint,
        reqConfig.method ?? "POST",
      );
    }

    const data = await res.json();
    kd(
      "auth",
      "tokenExchange: raw response keys:",
      Object.keys(data as object),
    );
    const parsed = config.parseTokenResponse(data);
    if (!parsed.accessToken) {
      kd(
        "auth",
        "tokenExchange: WARNING - accessToken is undefined/null, check parseTokenResponse",
      );
      throw new Error(
        "Token exchange response did not include an access token",
      );
    }

    const token: StoredAuthToken = { accessToken: parsed.accessToken };
    if (parsed.expiresAt !== undefined) {
      token.expiresAt = parsed.expiresAt;
    } else if (parsed.expiresIn !== undefined) {
      token.expiresAt = Date.now() + parsed.expiresIn * 1000;
    }
    if (parsed.refreshToken !== undefined) {
      token.refreshToken = parsed.refreshToken;
    }
    if (parsed.tokenType !== undefined) {
      token.tokenType = parsed.tokenType;
    }
    cacheToken(token);
    await config.tokenStore?.set(token);
    kd(
      "auth",
      "tokenExchange: got token, expires in",
      parsed.expiresIn ?? "unknown",
      "seconds",
    );
    return token.accessToken;
  }

  return {
    type: "tokenExchange",
    async apply(headers: Headers) {
      if (isExpired()) {
        const loaded = await loadStoredToken();
        if (!loaded) {
          kd("auth", "tokenExchange: token expired or missing, refreshing");
          await fetchToken();
        }
      }
      headers.set("Authorization", `Bearer ${cachedToken}`);
      kd(
        "auth",
        "tokenExchange: applied bearer token",
        cachedToken ? `${cachedToken.slice(0, 8)}...` : "MISSING",
      );

      if (config.extraHeaders) {
        const vars = await config.getVariables();
        const extra = config.extraHeaders(vars);
        for (const [key, value] of Object.entries(extra)) {
          headers.set(key, value);
          kd("auth", "tokenExchange: set extra header", key);
        }
      }
    },
    async onUnauthorized() {
      kd("auth", "tokenExchange: 401 received, clearing cached token");
      await clearToken();
    },
    set baseUrl(url: string) {
      _baseUrl = url;
    },
  };
}

// ---------------------------------------------------------------------------
// Authorization-code + PKCE auth strategy
// ---------------------------------------------------------------------------

type MaybePromise<T> = T | Promise<T>;
type VarResolver<T> = T | ((vars: Record<string, string>) => MaybePromise<T>);

export interface AuthorizationCodeToken {
  accessToken: string;
  expiresIn?: number;
  expiresAt?: number;
  refreshToken?: string;
  tokenType?: string;
}

export interface AuthorizationCodeConfig {
  getVariables?: () => MaybePromise<Record<string, string>>;
  authorizationEndpoint: string;
  tokenEndpoint: string;
  clientId: VarResolver<string>;
  clientSecret?: VarResolver<string | undefined>;
  redirectUri: VarResolver<string>;
  scopes?: string[];
  pkce?: boolean | { challengeMethod?: "S256" | "plain" };
  tokenStore?: TokenStore;
  refreshBufferSeconds?: number;
  includeRedirectUriOnRefresh?: boolean;
  extraAuthorizeParams?: Record<string, string>;
  extraTokenParams?: Record<string, string>;
  parseTokenResponse?: (data: unknown) => AuthorizationCodeToken;
}

export interface AuthorizationUrlResult {
  url: string;
  state?: string;
  codeVerifier?: string;
  codeChallenge?: string;
}

export interface AuthorizationCodeUrlOptions {
  vars?: Record<string, string>;
  state?: string;
  scopes?: string[];
  redirectUri?: string;
  codeVerifier?: string;
  extraParams?: Record<string, string>;
}

export interface AuthorizationCodeExchangeOptions {
  vars?: Record<string, string>;
  redirectUri?: string;
  codeVerifier?: string;
  extraParams?: Record<string, string>;
}

export type AuthorizationCodeAuthStrategy = AuthStrategy & {
  getAuthorizationUrl(
    options?: AuthorizationCodeUrlOptions,
  ): Promise<AuthorizationUrlResult>;
  exchangeCode(
    code: string,
    options?: AuthorizationCodeExchangeOptions,
  ): Promise<StoredAuthToken>;
  clearToken(): Promise<void>;
};

export function authorizationCode(
  config: AuthorizationCodeConfig,
): AuthorizationCodeAuthStrategy {
  let cachedToken: StoredAuthToken | null = null;
  let _baseUrl = "";
  const refreshBuffer = (config.refreshBufferSeconds ?? 60) * 1000;

  function resolveEndpoint(endpoint: string): string {
    if (endpoint.startsWith("http://") || endpoint.startsWith("https://")) {
      return endpoint;
    }
    return `${_baseUrl.replace(/\/$/, "")}${endpoint.startsWith("/") ? "" : "/"}${endpoint}`;
  }

  async function getVars(
    override?: Record<string, string>,
  ): Promise<Record<string, string>> {
    return override ?? (await config.getVariables?.()) ?? {};
  }

  async function resolveValue<T>(
    value: VarResolver<T>,
    vars: Record<string, string>,
  ): Promise<T> {
    return typeof value === "function"
      ? await (value as (vars: Record<string, string>) => MaybePromise<T>)(vars)
      : value;
  }

  async function resolveOptionalValue<T>(
    value: VarResolver<T | undefined> | undefined,
    vars: Record<string, string>,
  ): Promise<T | undefined> {
    if (value === undefined) return undefined;
    return resolveValue(value, vars);
  }

  function isExpired(token: StoredAuthToken | null): boolean {
    if (!token?.accessToken) return true;
    if (token.expiresAt === undefined) return false;
    return Date.now() >= token.expiresAt - refreshBuffer;
  }

  function normalizeToken(token: AuthorizationCodeToken): StoredAuthToken {
    const stored: StoredAuthToken = { accessToken: token.accessToken };
    if (token.expiresAt !== undefined) {
      stored.expiresAt = token.expiresAt;
    } else if (token.expiresIn !== undefined) {
      stored.expiresAt = Date.now() + token.expiresIn * 1000;
    }
    if (token.refreshToken !== undefined)
      stored.refreshToken = token.refreshToken;
    if (token.tokenType !== undefined) stored.tokenType = token.tokenType;
    return stored;
  }

  function parseTokenResponse(data: unknown): AuthorizationCodeToken {
    if (config.parseTokenResponse) return config.parseTokenResponse(data);
    const value = data as Record<string, unknown>;
    const token = value["access_token"];
    if (typeof token !== "string" || token.length === 0) {
      throw new Error("OAuth token response did not include access_token");
    }
    const parsed: AuthorizationCodeToken = { accessToken: token };
    const expiresIn = value["expires_in"];
    if (typeof expiresIn === "number") parsed.expiresIn = expiresIn;
    const refreshToken = value["refresh_token"];
    if (typeof refreshToken === "string") parsed.refreshToken = refreshToken;
    const tokenType = value["token_type"];
    if (typeof tokenType === "string") parsed.tokenType = tokenType;
    return parsed;
  }

  async function saveToken(token: StoredAuthToken): Promise<StoredAuthToken> {
    cachedToken = token;
    await config.tokenStore?.set(token);
    return token;
  }

  async function loadToken(): Promise<StoredAuthToken | null> {
    if (cachedToken && !isExpired(cachedToken)) return cachedToken;
    const stored = await config.tokenStore?.get();
    if (stored?.accessToken) {
      cachedToken = stored;
      if (!isExpired(stored)) return stored;
    }
    return cachedToken;
  }

  async function clearToken(): Promise<void> {
    cachedToken = null;
    await config.tokenStore?.clear?.();
  }

  async function requestToken(body: URLSearchParams): Promise<StoredAuthToken> {
    const endpoint = resolveEndpoint(config.tokenEndpoint);
    const response = await fetch(endpoint, {
      method: "POST",
      headers: new Headers({
        "Content-Type": "application/x-www-form-urlencoded",
      }),
      body,
    });
    if (!response.ok) {
      const text = await response.text().catch(() => "");
      throw new PlugError(
        `OAuth token request failed: ${response.status} ${response.statusText}`,
        response.status,
        response.statusText,
        text,
        endpoint,
        "POST",
      );
    }
    const token = normalizeToken(parseTokenResponse(await response.json()));
    return saveToken(token);
  }

  async function refreshToken(
    token: StoredAuthToken,
    vars: Record<string, string>,
  ): Promise<StoredAuthToken> {
    if (!token.refreshToken) {
      throw new Error("OAuth token is expired and no refresh token is stored");
    }
    const body = new URLSearchParams({
      grant_type: "refresh_token",
      refresh_token: token.refreshToken,
      client_id: await resolveValue(config.clientId, vars),
      ...config.extraTokenParams,
    });
    if (config.includeRedirectUriOnRefresh) {
      body.set("redirect_uri", await resolveValue(config.redirectUri, vars));
    }
    const clientSecret = await resolveOptionalValue(config.clientSecret, vars);
    if (clientSecret) body.set("client_secret", clientSecret);
    const refreshed = await requestToken(body);
    if (!refreshed.refreshToken) {
      refreshed.refreshToken = token.refreshToken;
      await saveToken(refreshed);
    }
    return refreshed;
  }

  const strategy: AuthorizationCodeAuthStrategy = {
    type: "authorizationCode",
    async getAuthorizationUrl(options = {}) {
      const vars = await getVars(options.vars);
      const url = new URL(resolveEndpoint(config.authorizationEndpoint));
      url.searchParams.set("response_type", "code");
      url.searchParams.set(
        "client_id",
        await resolveValue(config.clientId, vars),
      );
      url.searchParams.set(
        "redirect_uri",
        options.redirectUri ?? (await resolveValue(config.redirectUri, vars)),
      );
      const scopes = options.scopes ?? config.scopes;
      if (scopes?.length) url.searchParams.set("scope", scopes.join(" "));
      if (options.state) url.searchParams.set("state", options.state);
      for (const [key, value] of Object.entries(
        config.extraAuthorizeParams ?? {},
      )) {
        url.searchParams.set(key, value);
      }
      for (const [key, value] of Object.entries(options.extraParams ?? {})) {
        url.searchParams.set(key, value);
      }

      const result: AuthorizationUrlResult = { url: "" };
      if (options.state) result.state = options.state;
      if (config.pkce) {
        const verifier = options.codeVerifier ?? createPkceVerifier();
        const method =
          typeof config.pkce === "object"
            ? (config.pkce.challengeMethod ?? "S256")
            : "S256";
        const challenge =
          method === "plain" ? verifier : await createPkceChallenge(verifier);
        url.searchParams.set("code_challenge", challenge);
        url.searchParams.set("code_challenge_method", method);
        result.codeVerifier = verifier;
        result.codeChallenge = challenge;
      }
      result.url = url.toString();
      return result;
    },
    async exchangeCode(code, options = {}) {
      const vars = await getVars(options.vars);
      const body = new URLSearchParams({
        grant_type: "authorization_code",
        code,
        client_id: await resolveValue(config.clientId, vars),
        redirect_uri:
          options.redirectUri ?? (await resolveValue(config.redirectUri, vars)),
        ...config.extraTokenParams,
        ...options.extraParams,
      });
      const clientSecret = await resolveOptionalValue(
        config.clientSecret,
        vars,
      );
      if (clientSecret) body.set("client_secret", clientSecret);
      if (options.codeVerifier) body.set("code_verifier", options.codeVerifier);
      return requestToken(body);
    },
    async apply(headers, vars) {
      const resolvedVars = await getVars(vars);
      let token = await loadToken();
      if (isExpired(token)) {
        if (token?.refreshToken) {
          token = await refreshToken(token, resolvedVars);
        } else {
          throw new Error(
            "OAuth authorization code token is expired or missing. Call exchangeCode() before making API requests.",
          );
        }
      }
      if (!token?.accessToken) {
        throw new Error(
          "OAuth authorization code token is missing. Call exchangeCode() before making API requests.",
        );
      }
      headers.set("Authorization", `Bearer ${token.accessToken}`);
    },
    async onUnauthorized(vars) {
      const token = await loadToken();
      if (token?.refreshToken) {
        await refreshToken(token, await getVars(vars));
        return;
      }
      await clearToken();
    },
    clearToken,
    set baseUrl(url: string) {
      _baseUrl = url;
    },
  };

  return strategy;
}

// ---------------------------------------------------------------------------
// Pagination strategies
// ---------------------------------------------------------------------------

export interface PaginationStrategy {
  type: string;
  getNextParams(
    response: Record<string, unknown>,
    currentParams: Record<string, unknown>,
  ): Record<string, unknown> | null;
  getDataPath(): string;
}

function getByPath(obj: Record<string, unknown>, path: string): unknown {
  return path.split(".").reduce<unknown>((acc, key) => {
    if (acc != null && typeof acc === "object") {
      return (acc as Record<string, unknown>)[key];
    }
    return undefined;
  }, obj);
}

export function cursorPagination(config: {
  cursorParam: string;
  cursorPath: string;
  dataPath: string;
}): PaginationStrategy {
  return {
    type: "cursor",
    getNextParams(response) {
      const cursor = getByPath(response, config.cursorPath);
      if (cursor == null || cursor === "") return null;
      return { [config.cursorParam]: cursor };
    },
    getDataPath() {
      return config.dataPath;
    },
  };
}

export function offsetPagination(config: {
  limitParam?: string;
  offsetParam?: string;
  dataPath: string;
  pageSize: number;
}): PaginationStrategy {
  const limitParam = config.limitParam ?? "limit";
  const offsetParam = config.offsetParam ?? "offset";
  return {
    type: "offset",
    getNextParams(_response, currentParams) {
      const data = getByPath(_response, config.dataPath) as
        | unknown[]
        | undefined;
      if (!data || data.length < config.pageSize) return null;
      const currentOffset =
        typeof currentParams[offsetParam] === "number"
          ? (currentParams[offsetParam] as number)
          : 0;
      return {
        [limitParam]: config.pageSize,
        [offsetParam]: currentOffset + config.pageSize,
      };
    },
    getDataPath() {
      return config.dataPath;
    },
  };
}

export function keysetPagination(config: {
  param: string;
  idField: string;
  dataPath: string;
}): PaginationStrategy {
  return {
    type: "keyset",
    getNextParams(response) {
      const data = getByPath(response, config.dataPath) as
        | Record<string, unknown>[]
        | undefined;
      if (!data || data.length === 0) return null;
      const lastItem = data[data.length - 1];
      const id = lastItem?.[config.idField];
      if (id == null) return null;
      return { [config.param]: id };
    },
    getDataPath() {
      return config.dataPath;
    },
  };
}

// ---------------------------------------------------------------------------
// Retry logic
// ---------------------------------------------------------------------------

interface RetryConfig {
  attempts: number;
  backoff?: number;
  maxBackoff?: number;
  retryableStatuses?: number[];
}

const DEFAULT_RETRY: RetryConfig = {
  attempts: 3,
  backoff: 1000,
  maxBackoff: 30000,
  retryableStatuses: [408, 429, 500, 502, 503, 504],
};

function computeDelay(attempt: number, config: RetryConfig): number {
  const base = config.backoff ?? 1000;
  const max = config.maxBackoff ?? 30000;
  const exponential = base * Math.pow(2, attempt);
  const jitter = Math.random() * exponential * 0.1;
  return Math.min(exponential + jitter, max);
}

function parseRetryAfter(header: string | null): number | null {
  if (!header) return null;
  const seconds = Number(header);
  if (!Number.isNaN(seconds)) return seconds * 1000;
  const date = Date.parse(header);
  if (!Number.isNaN(date)) return Math.max(0, date - Date.now());
  return null;
}

// ---------------------------------------------------------------------------
// Hooks
// ---------------------------------------------------------------------------

export interface HookContext<Vars = Record<string, string>> {
  url: string;
  path: string;
  method: string;
  headers: Headers;
  body?: unknown;
  vars: Vars;
  setVars(updates: Partial<Vars>): Promise<void>;
}

export interface PlugHooks<Vars = Record<string, string>> {
  beforeRequest?: (ctx: HookContext<Vars>) => void | Promise<void>;
  afterResponse?: (
    response: Response,
    ctx: HookContext<Vars>,
  ) => void | Promise<void>;
}

// ---------------------------------------------------------------------------
// Wire configuration
// ---------------------------------------------------------------------------

export interface EndpointSchema {
  parse(data: unknown): unknown;
  _def?: unknown;
  shape?: Record<string, unknown>;
}

export interface EndpointDef {
  method: string;
  path: string;
  description?: string;
  body?: EndpointSchema;
  query?: EndpointSchema;
  responses?: Record<number, EndpointSchema>;
}

export interface PlugConfig<V extends readonly VarField[] = VarField[]> {
  name?: string;
  /**
   * Base URL for the connector. Pass a string for a single fixed host, or a
   * function of the plug's bound vars to resolve the host per environment /
   * tenant at request time (e.g. `(vars) => vars.baseUrl ?? PROD_URL`). The
   * debug/probe route binds the same vars, so it targets the same host a flow
   * would — no probe/flow divergence.
   */
  baseUrl: string | ((vars: VarsRecord<V>) => string);
  auth?: AuthStrategy;
  vars?: V;
  endpoints?: Record<string, EndpointDef>;
  retry?: RetryConfig | false;
  timeout?: number;
  defaultHeaders?: Record<string, string>;
  pagination?: PaginationStrategy;
  hooks?: PlugHooks<VarsRecord<V>>;
  parsers?: Record<string, (text: string) => unknown>;
}

export interface RequestOptions {
  params?: Record<string, unknown>;
  body?: unknown;
  headers?: Record<string, string>;
  signal?: AbortSignal;
  /** Injected vars available in hooks via ctx.vars */
  vars?: Record<string, string>;
  /** Function to persist var updates back to encrypted storage */
  _setVars?: (updates: Record<string, string>) => Promise<void>;
  /** @internal Skip hooks for this request (used to prevent recursion in beforeRequest) */
  _skipHooks?: boolean;
}

export interface BatchPostOptions<TRecord = unknown> {
  /** Records per POST body. Defaults to 100. */
  batchSize?: number;
  /** Number of batches to post in parallel. Defaults to 1. */
  concurrency?: number;
  headers?: Record<string, string>;
  signal?: AbortSignal;
  /** Shape each request body. Defaults to sending the batch array directly. */
  buildBody?: (records: TRecord[], batchIndex: number) => unknown;
}

// ---------------------------------------------------------------------------
// Plug class
// ---------------------------------------------------------------------------

export class Plug<V extends readonly VarField[] = VarField[]> {
  private readonly config: PlugConfig<V>;

  constructor(config: PlugConfig<V>) {
    this.config = config;
    // For a static baseUrl, seed the auth strategy once (used to resolve
    // relative token endpoints). For a dynamic (function) baseUrl, the auth
    // baseUrl is refreshed per request in request() from the bound vars.
    if (config.auth && typeof config.baseUrl === "string") {
      config.auth.baseUrl = config.baseUrl;
    }
  }

  get name(): string {
    return this.config.name ?? "unnamed";
  }

  get baseUrl(): string {
    return this.resolveBaseUrl();
  }

  /**
   * Resolve the effective base URL. When `baseUrl` is a function it is invoked
   * with the request's bound vars, enabling per-environment / per-tenant hosts
   * sourced from plug vars. Flows and the debug/probe route both pass their
   * bound vars, so they resolve to the same host.
   */
  resolveBaseUrl(vars?: Record<string, string>): string {
    const { baseUrl } = this.config;
    return typeof baseUrl === "function"
      ? baseUrl((vars ?? {}) as VarsRecord<V>)
      : baseUrl;
  }

  get authType(): string {
    return this.config.auth?.type ?? "none";
  }

  get varFields(): readonly VarField[] {
    return this.config.vars ?? [];
  }

  get endpoints(): Record<string, EndpointDef> {
    return this.config.endpoints ?? {};
  }

  async get<T>(path: string, options?: RequestOptions): Promise<T> {
    return this.request<T>("GET", path, options);
  }

  async post<T>(path: string, options?: RequestOptions): Promise<T> {
    return this.request<T>("POST", path, options);
  }

  async batchPost<TResponse = unknown, TRecord = unknown>(
    path: string,
    records: readonly TRecord[],
    options?: BatchPostOptions<TRecord>,
  ): Promise<TResponse[]> {
    const batchSize = options?.batchSize ?? 100;
    const concurrency = options?.concurrency ?? 1;
    if (batchSize < 1) throw new Error("batchSize must be at least 1");
    if (concurrency < 1) throw new Error("concurrency must be at least 1");
    if (records.length === 0) return [];

    const batches: TRecord[][] = [];
    for (let i = 0; i < records.length; i += batchSize) {
      batches.push(records.slice(i, i + batchSize));
    }

    const results: TResponse[] = new Array<TResponse>(batches.length);
    let next = 0;

    const worker = async () => {
      while (next < batches.length) {
        const index = next++;
        const batch = batches[index]!;
        results[index] = await this.post<TResponse>(path, {
          body: options?.buildBody ? options.buildBody(batch, index) : batch,
          headers: options?.headers,
          signal: options?.signal,
        });
      }
    };

    await Promise.all(
      Array.from({ length: Math.min(concurrency, batches.length) }, () =>
        worker(),
      ),
    );
    return results;
  }

  async put<T>(path: string, options?: RequestOptions): Promise<T> {
    return this.request<T>("PUT", path, options);
  }

  async patch<T>(path: string, options?: RequestOptions): Promise<T> {
    return this.request<T>("PATCH", path, options);
  }

  async delete<T>(path: string, options?: RequestOptions): Promise<T> {
    return this.request<T>("DELETE", path, options);
  }

  async request<T>(
    method: string,
    path: string,
    options?: RequestOptions,
  ): Promise<T> {
    const base = this.resolveBaseUrl(options?.vars);
    // Refresh the auth strategy's baseUrl per request when it's dynamic, so
    // relative token endpoints resolve against the current environment.
    if (this.config.auth && typeof this.config.baseUrl === "function") {
      this.config.auth.baseUrl = base;
    }
    const url = this.buildUrl(base, path, options?.params);
    const headers = this.buildHeaders(options?.headers);

    if (!options?._skipHooks && this.config.hooks?.beforeRequest) {
      const setVars = options?._setVars ?? (async () => {});
      await this.config.hooks.beforeRequest({
        url,
        path,
        method,
        headers,
        body: options?.body,
        vars: (options?.vars ?? {}) as VarsRecord<V>,
        setVars: (updates) => setVars(updates as Record<string, string>),
      });
    }

    if (this.config.auth) {
      await this.config.auth.apply(
        headers,
        options?.vars,
        this.buildAuthContext(method, url, options),
      );
    }

    const queryParam = this.config.auth?.queryParam;
    if (queryParam) {
      const u = new URL(url);
      u.searchParams.set(queryParam.name, queryParam.value);
      return this._fetchWithAuthRetry<T>(
        method,
        u.toString(),
        headers,
        options,
      );
    }

    return this._fetchWithAuthRetry<T>(method, url, headers, options);
  }

  async *paginate<T>(
    path: string,
    options?: RequestOptions,
  ): AsyncIterable<T[]> {
    const pagination = this.config.pagination;
    if (!pagination) {
      throw new Error(
        "Pagination strategy must be configured to use paginate()",
      );
    }

    let currentParams: Record<string, unknown> = { ...options?.params };

    while (true) {
      const response = await this.request<Record<string, unknown>>(
        "GET",
        path,
        { ...options, params: currentParams },
      );

      const data = getByPath(response, pagination.getDataPath()) as
        | T[]
        | undefined;
      if (!data || data.length === 0) break;

      yield data;

      const nextParams = pagination.getNextParams(response, currentParams);
      if (!nextParams) break;

      currentParams = { ...currentParams, ...nextParams };
    }
  }

  with(overrides: Partial<PlugConfig<V>>): Plug<V> {
    return new Plug({ ...this.config, ...overrides });
  }

  withAuth(auth: AuthStrategy): Plug<V> {
    return this.with({ auth });
  }

  private buildUrl(
    base: string,
    path: string,
    params?: Record<string, unknown>,
  ): string {
    const trimmedBase = base.replace(/\/+$/, "");
    const cleanPath = path.startsWith("/") ? path : `/${path}`;
    const url = new URL(`${trimmedBase}${cleanPath}`);

    if (params) {
      for (const [key, value] of Object.entries(params)) {
        if (value != null) {
          url.searchParams.set(key, String(value));
        }
      }
    }

    return url.toString();
  }

  private buildHeaders(extra?: Record<string, string>): Headers {
    const headers = new Headers();

    if (this.config.defaultHeaders) {
      for (const [key, value] of Object.entries(this.config.defaultHeaders)) {
        headers.set(key, value);
      }
    }

    if (extra) {
      for (const [key, value] of Object.entries(extra)) {
        headers.set(key, value);
      }
    }

    return headers;
  }

  private buildAuthContext(
    method: string,
    url: string,
    options?: RequestOptions,
  ): AuthApplyContext<VarsRecord<V>> {
    const parsed = new URL(url);
    return {
      url,
      query: parsed.searchParams.toString(),
      searchParams: parsed.searchParams,
      method,
      body: options?.body,
      vars: (options?.vars ?? {}) as VarsRecord<V>,
    };
  }

  private async _fetchWithAuthRetry<T>(
    method: string,
    url: string,
    headers: Headers,
    options?: RequestOptions,
  ): Promise<T> {
    try {
      return await this._fetch<T>(method, url, headers, options);
    } catch (error) {
      if (
        error instanceof PlugError &&
        error.status === 401 &&
        this.config.auth?.onUnauthorized
      ) {
        kd(
          "request",
          `${this.name}: 401 on ${method} ${url}, retrying with fresh auth`,
        );
        const authContext = this.buildAuthContext(method, url, options);
        await this.config.auth.onUnauthorized(options?.vars, authContext);
        const freshHeaders = this.buildHeaders(options?.headers);
        await this.config.auth.apply(freshHeaders, options?.vars, authContext);
        return this._fetch<T>(method, url, freshHeaders, options);
      }
      throw error;
    }
  }

  private async _fetch<T>(
    method: string,
    url: string,
    headers: Headers,
    options?: RequestOptions,
  ): Promise<T> {
    kd("request", `${this.name}: ${method} ${url}`);
    const retryConfig =
      this.config.retry === false
        ? null
        : { ...DEFAULT_RETRY, ...this.config.retry };

    const maxAttempts = retryConfig ? retryConfig.attempts : 1;

    let lastError: Error | undefined;

    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      try {
        const controller = new AbortController();
        let timeoutId: ReturnType<typeof setTimeout> | undefined;

        if (this.config.timeout) {
          timeoutId = setTimeout(() => controller.abort(), this.config.timeout);
        }

        const externalSignal = options?.signal;
        if (externalSignal?.aborted) {
          controller.abort(externalSignal.reason);
        }
        externalSignal?.addEventListener("abort", () =>
          controller.abort(externalSignal.reason),
        );

        const init: globalThis.RequestInit = {
          method,
          headers,
          signal: controller.signal,
        };

        if (options?.body !== undefined && method !== "GET") {
          init.body = JSON.stringify(options.body);
          headers.set("Content-Type", "application/json");
        }

        const response = await fetch(url, init);

        if (timeoutId) clearTimeout(timeoutId);

        if (this.config.hooks?.afterResponse && !options?._skipHooks) {
          const setVars = options?._setVars ?? (async () => {});
          await this.config.hooks.afterResponse(response.clone(), {
            url,
            path: url.replace(
              this.resolveBaseUrl(options?.vars).replace(/\/+$/, ""),
              "",
            ),
            method,
            headers,
            body: options?.body,
            vars: (options?.vars ?? {}) as VarsRecord<V>,
            setVars: (updates) => setVars(updates as Record<string, string>),
          });
        }

        if (!response.ok) {
          const body = await response.text().catch(() => "");
          const plugError = new PlugError(
            `${method} ${url} failed with ${response.status} ${response.statusText}`,
            response.status,
            response.statusText,
            body,
            url,
            method,
          );

          if (
            retryConfig &&
            attempt < maxAttempts - 1 &&
            (retryConfig.retryableStatuses?.includes(response.status) ?? false)
          ) {
            let delay = computeDelay(attempt, retryConfig);

            if (response.status === 429) {
              const retryAfter = parseRetryAfter(
                response.headers.get("Retry-After"),
              );
              if (retryAfter !== null) {
                delay = retryAfter;
              }
            }

            lastError = plugError;
            await sleep(delay);
            continue;
          }

          throw plugError;
        }

        const contentType = response.headers.get("Content-Type") ?? "";
        if (contentType.includes("application/json")) {
          return (await response.json()) as T;
        }

        if (this.config.parsers) {
          for (const [mime, parser] of Object.entries(this.config.parsers)) {
            if (contentType.includes(mime)) {
              const text = await response.text();
              return parser(text) as T;
            }
          }
        }

        return (await response.text()) as unknown as T;
      } catch (error) {
        if (error instanceof PlugError) throw error;

        if (
          retryConfig &&
          attempt < maxAttempts - 1 &&
          !(error instanceof DOMException && error.name === "AbortError")
        ) {
          lastError = error as Error;
          await sleep(computeDelay(attempt, retryConfig));
          continue;
        }

        if (error instanceof DOMException && error.name === "AbortError") {
          throw new Error(`Request timed out: ${method} ${url}`, {
            cause: error,
          });
        }

        throw error;
      }
    }

    throw (
      lastError ?? new Error(`Request failed after ${maxAttempts} attempts`)
    );
  }
}

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

export function plug<const V extends readonly VarField[]>(
  config: PlugConfig<V>,
): Plug<V> {
  return new Plug(config);
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function createPkceVerifier(): string {
  const bytes = new Uint8Array(32);
  if (!globalThis.crypto?.getRandomValues) {
    throw new Error("PKCE requires globalThis.crypto.getRandomValues");
  }
  globalThis.crypto.getRandomValues(bytes);
  return base64UrlEncode(bytes);
}

async function createPkceChallenge(verifier: string): Promise<string> {
  if (!globalThis.crypto?.subtle) {
    throw new Error("PKCE S256 requires globalThis.crypto.subtle");
  }
  const digest = await globalThis.crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(verifier),
  );
  return base64UrlEncode(new Uint8Array(digest));
}

function base64UrlEncode(bytes: Uint8Array): string {
  let binary = "";
  for (const byte of bytes) {
    binary += String.fromCharCode(byte);
  }
  return btoa(binary)
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/g, "");
}
