// ============================================================================
// Relay — durable external service → external service data movement
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file keeps local imports stable while reusing the real builder and types
// from khotan-data/factory. Create per-service flow files using relay() to read
// from the source plug and forward to a destination system with durable,
// retryable Vercel Workflow steps.
// ============================================================================

export { relay } from "khotan-data/factory";

export type {
  FlowRegistration,
  FlowRunResult,
  FlowVariant,
  RelayConfig,
  RelayContext,
  RelayWorkflow,
} from "khotan-data/factory";

// ---------------------------------------------------------------------------
// Usage Example (create a file like flows/shopify-to-hubspot.ts)
// ---------------------------------------------------------------------------
//
// Declare "use step" functions at MODULE TOP LEVEL and pass them serializable
// values only (`ctx` is plain data). Do NOT nest steps inside the "use workflow"
// function — closures over workflow scope cannot be hoisted and fail at runtime.
//
// import { bindWorkflowPlug, khotanCache, relay, type RelayContext } from "khotan-data/factory";
// import { shopifyPlug } from "../plugs/shopify";
// import { hubspotPlug } from "../plugs/hubspot";
//
// // Step: top-level, full Node.js access, retried independently.
// async function forwardProducts(ctx: RelayContext) {
//   "use step";
//   console.log("Starting relay", {
//     flow: ctx.flow.name,
//     to: ctx.flow.to,
//     khotanRunId: ctx.khotanRunId,
//     variant: ctx.variant,
//   });
//   const shopify = bindWorkflowPlug(shopifyPlug, ctx);
//   const hubspot = bindWorkflowPlug(hubspotPlug, ctx, "hubspot");
//
//   const snapshotCache = khotanCache(ctx, "shopify-products-snapshot");
//   const previous = await snapshotCache.get<Array<Record<string, unknown>>>("latest");
//
//   const response = await shopify.get<{ data?: Array<Record<string, unknown>> }>("/products");
//   const records = Array.isArray(response.data) ? response.data : [];
//   await snapshotCache.set("latest", records);
//
//   for (const record of records) {
//     await hubspot.post("/products", { body: record });
//   }
//
//   return {
//     extracted: records.length,
//     transformed: records.length,
//     created: records.length,
//     metadata: {
//       relay: ctx.flow.name,
//       to: ctx.flow.to,
//       previousCount: previous?.length ?? 0,
//     },
//   };
// }
//
// // Workflow: orchestration only.
// async function shopifyToHubspotWorkflow(ctx: RelayContext) {
//   "use workflow";
//   return forwardProducts(ctx);
// }
//
// export const shopifyToHubspotRelay = relay({
//   name: "shopify-to-hubspot-products",
//   to: "hubspot",
//   resource: "products",
//   schedule: "0 * * * *",
//   workflow: shopifyToHubspotWorkflow,
// });
