// ============================================================================
// Example: Relay
// Generated by khotan CLI · https://github.com/khotan-data
//
// Copy this file, rename it for your source/destination pair, and register the
// exported flow in {outputDir}/khotan.ts.
//
// IMPORTANT — Workflow step structure:
// Declare "use step" functions at module top level and pass them only
// serializable values (the `ctx` object is plain data and is safe to pass).
// Do NOT nest step functions inside the "use workflow" function — the Workflow
// compiler cannot hoist closures that capture workflow scope, and they fail at
// runtime in the sandbox. Keep the workflow body limited to orchestration.
// ============================================================================

import { khotanCache } from "khotan-data/factory";
import { relay, type RelayContext } from "./relay";

// Step: full Node.js access, retried independently. Receives serializable ctx.
async function forwardProducts(ctx: RelayContext) {
  "use step";
  console.log("Starting relay", {
    flow: ctx.flow.name,
    to: ctx.flow.to,
    khotanRunId: ctx.khotanRunId,
    variant: ctx.variant,
  });

  const sourceResponse = await fetch("https://source.example.com/products", {
    headers: {
      Authorization: `Bearer ${ctx.vars["sourceToken"] ?? ""}`,
    },
  });
  const payload = (await sourceResponse.json()) as {
    data?: Array<Record<string, unknown>>;
  };
  const records = Array.isArray(payload.data) ? payload.data : [];
  const snapshotCache = khotanCache(ctx, "shopify-products-snapshot");
  const previousRecords =
    (await snapshotCache.get<Array<Record<string, unknown>>>("latest")) ?? [];

  // TTL is configured on the cache definition (CacheRegistration.ttl), not per set().
  await snapshotCache.set("latest", records);

  for (const record of records) {
    await fetch("https://destination.example.com/products", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${ctx.vars["destinationToken"] ?? ""}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(record),
    });
  }

  return {
    extracted: records.length,
    transformed: records.length,
    created: records.length,
    metadata: {
      relay: ctx.flow.name,
      to: ctx.flow.to,
      previousCount: previousRecords.length,
    },
  };
}

// Workflow: orchestration only. Calls top-level steps with serializable args.
async function shopifyToHubspotWorkflow(ctx: RelayContext) {
  "use workflow";
  return forwardProducts(ctx);
}

export const shopifyToHubspotRelay = relay({
  name: "shopify-to-hubspot-products",
  to: "hubspot",
  resource: "products",
  schedule: "0 * * * *",
  workflow: shopifyToHubspotWorkflow,
});
