// ============================================================================
// Example: Relay
// Generated by khotan CLI · https://github.com/khotan-data
//
// Copy this file, rename it for your source/destination pair, and register the
// exported flow in {outputDir}/khotan.ts.
// ============================================================================

import { khotanCache } from "khotan-data/factory";
import { relay, type RelayContext } from "./relay";

async function shopifyToHubspotWorkflow(ctx: RelayContext) {
  "use workflow";

  async function forwardProducts() {
    "use step";
    console.log("Starting relay", {
      flow: ctx.flow.name,
      to: ctx.flow.to,
      khotanRunId: ctx.khotanRunId,
      runType: ctx.runType,
    });

    const sourceResponse = await fetch("https://source.example.com/products", {
      headers: {
        Authorization: `Bearer ${ctx.vars["sourceToken"] ?? ""}`,
      },
    });
    const payload = (await sourceResponse.json()) as {
      data?: Array<Record<string, unknown>>;
    };
    const records = Array.isArray(payload.data) ? payload.data : [];
    const snapshotCache = khotanCache(ctx, "shopify-products-snapshot");
    const previousRecords =
      (await snapshotCache.get<Array<Record<string, unknown>>>("latest")) ?? [];

    await snapshotCache.set("latest", records, { ttl: "6h" });

    for (const record of records) {
      await fetch("https://destination.example.com/products", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${ctx.vars["destinationToken"] ?? ""}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(record),
      });
    }

    return {
      extracted: records.length,
      transformed: records.length,
      created: records.length,
      metadata: {
        relay: ctx.flow.name,
        to: ctx.flow.to,
        previousCount: previousRecords.length,
      },
    };
  }

  return forwardProducts();
}

export const shopifyToHubspotRelay = relay({
  name: "shopify-to-hubspot-products",
  to: "hubspot",
  resource: "products",
  schedule: "0 * * * *",
  workflow: shopifyToHubspotWorkflow,
});
