// ============================================================================
// Example: Relay
// Generated by khotan CLI · https://github.com/khotan-data
//
// Copy this file, rename it for your source/destination pair, and register the
// exported flow in {outputDir}/khotan.ts.
// ============================================================================

import { shopifyPlug } from "../plugs/shopify";
import { hubspotPlug } from "../plugs/hubspot";
import { relay, type RelayContext } from "./relay";

async function shopifyToHubspotWorkflow(ctx: RelayContext) {
  "use workflow";

  async function forwardProducts() {
    "use step";
    console.log("Starting relay", {
      flow: ctx.flow.name,
      to: ctx.flow.to,
      khotanRunId: ctx.khotanRunId,
      runType: ctx.runType,
    });

    const response = await shopifyPlug.get<{
      data?: Array<Record<string, unknown>>;
    }>("/products", {
      vars: ctx.vars,
    });
    const records = Array.isArray(response.data) ? response.data : [];

    for (const record of records) {
      await hubspotPlug.post("/products", { body: record });
    }

    return {
      extracted: records.length,
      transformed: records.length,
      created: records.length,
      metadata: { relay: ctx.flow.name, to: ctx.flow.to },
    };
  }

  return forwardProducts();
}

export const shopifyToHubspotRelay = relay({
  name: "shopify-to-hubspot-products",
  to: "hubspot",
  resource: "products",
  schedule: "0 * * * *",
  workflow: shopifyToHubspotWorkflow,
});
