// ============================================================================
// Relay — durable external service → external service data movement
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file defines the relay() builder and types. Create per-service flow
// files (e.g. shopify-to-hubspot.ts) using this builder to read from the source
// plug and forward to a destination system with durable, retryable Vercel
// Workflow steps. Relay workflows can also use khotanCache(ctx, "name") for durable
// snapshots, checkpoints, and dedupe state between runs.
// ============================================================================

import type {
  FlowRegistration,
  FlowRunResult,
  FlowWorkflowContext,
} from "khotan-data/factory";

export type RelayContext = FlowWorkflowContext & {
  flow: FlowWorkflowContext["flow"] & { type: "relay"; to?: string | null };
};

export type RelayWorkflow = (
  ctx: RelayContext,
) => Promise<FlowRunResult | void>;

export interface RelayConfig {
  /** Unique name for this flow (used for DB tracking and Hub display) */
  name: string;
  /** Name of the destination plug/system for humans and future tooling */
  to: string;
  /** Logical resource this flow moves, e.g. "products" */
  resource?: string;
  /** Optional cron schedule used by scheduler integrations */
  schedule?: string;
  /** Durable workflow that reads from source and writes to destination */
  workflow: RelayWorkflow;
}

export function relay(config: RelayConfig): FlowRegistration {
  return {
    name: config.name,
    type: "relay",
    to: config.to,
    resource: config.resource,
    schedule: config.schedule,
    workflow: config.workflow as FlowRegistration["workflow"],
  };
}

// ---------------------------------------------------------------------------
// Usage Example (create a file like flows/shopify-to-hubspot.ts)
// ---------------------------------------------------------------------------
//
// import { bindWorkflowPlug, khotanCache, relay, type RelayContext } from "khotan-data/factory";
// import { shopifyPlug } from "../plugs/shopify";
// import { hubspotPlug } from "../plugs/hubspot";
//
// async function shopifyToHubspotWorkflow(ctx: RelayContext) {
//   "use workflow";
//
//   async function forwardProducts() {
//     "use step";
//     console.log("Starting relay", {
//       flow: ctx.flow.name,
//       to: ctx.flow.to,
//       khotanRunId: ctx.khotanRunId,
//       runType: ctx.runType,
//     });
//     const shopify = bindWorkflowPlug(shopifyPlug, ctx);
//     const hubspot = bindWorkflowPlug(hubspotPlug, ctx, "hubspot");
//
//     const snapshotCache = khotanCache(ctx, "shopify-products-snapshot");
//     const previous = await snapshotCache.get<Array<Record<string, unknown>>>("latest");
//
//     const response = await shopify.get<{ data?: Array<Record<string, unknown>> }>("/products");
//     const records = Array.isArray(response.data) ? response.data : [];
//     await snapshotCache.set("latest", records);
//
//     for (const record of records) {
//       await hubspot.post("/products", { body: record });
//     }
//
//     return {
//       extracted: records.length,
//       transformed: records.length,
//       created: records.length,
//       metadata: {
//         relay: ctx.flow.name,
//         to: ctx.flow.to,
//         previousCount: previous?.length ?? 0,
//       },
//     };
//   }
//
//   return forwardProducts();
// }
//
// export const shopifyToHubspotRelay = relay({
//   name: "shopify-to-hubspot-products",
//   to: "hubspot",
//   resource: "products",
//   schedule: "0 * * * *",
//   workflow: shopifyToHubspotWorkflow,
// });
