// ============================================================================
// Schema — Drizzle table definitions for khotan plugs, syncs, and runs
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file is yours. Edit anything — column types, defaults, indexes,
// relations. It has zero runtime dependencies on khotan-data.
//
// Re-export from your Drizzle schema barrel file:
//   export * from "@/lib/khotan/schema";
// ============================================================================

import { relations } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";

// ---------------------------------------------------------------------------
// khotan_plugs — one row per configured external service connection
// ---------------------------------------------------------------------------

export const khotanPlugs = pgTable("khotan_plugs", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  name: text("name").notNull().unique(),
  baseUrl: text("base_url").notNull(),
  authType: text("auth_type", {
    enum: ["bearer", "basic", "apiKey", "custom"],
  }).notNull(),
  enabled: boolean("enabled").default(true).notNull(),
  status: text("status", {
    enum: ["connected", "error", "idle"],
  })
    .default("idle")
    .notNull(),
  statusMessage: text("status_message"),
  encryptedCredentials: text("encrypted_credentials"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

// ---------------------------------------------------------------------------
// khotan_resources — one row per logical entity type (e.g. products, orders)
// ---------------------------------------------------------------------------

export const khotanResources = pgTable("khotan_resources", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  name: text("name").notNull().unique(),
  connectField: text("connect_field").notNull(),
  description: text("description"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

// ---------------------------------------------------------------------------
// khotan_syncs — one row per data flow tied to a plug
// ---------------------------------------------------------------------------

export const khotanSyncs = pgTable(
  "khotan_syncs",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    plugId: text("plug_id")
      .notNull()
      .references(() => khotanPlugs.id),
    name: text("name").notNull(),
    type: text("type", {
      enum: ["inflow", "outflow", "relay", "webhook"],
    }).notNull(),
    enabled: boolean("enabled").default(true).notNull(),
    schedule: text("schedule"),
    resourceId: text("resource_id").references(() => khotanResources.id),
    lastRunAt: timestamp("last_run_at", { withTimezone: true }),
    lastRunStatus: text("last_run_status", {
      enum: ["ok", "failed"],
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    unique("khotan_syncs_plug_id_name_unique").on(table.plugId, table.name),
    index("khotan_syncs_plug_id_idx").on(table.plugId),
    index("khotan_syncs_resource_id_idx").on(table.resourceId),
  ],
);

// ---------------------------------------------------------------------------
// khotan_runs — one row per execution of a sync
// ---------------------------------------------------------------------------

export const khotanRuns = pgTable(
  "khotan_runs",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    syncId: text("sync_id")
      .notNull()
      .references(() => khotanSyncs.id),
    runType: text("run_type", {
      enum: ["full", "delta", "backfill", "reconcile", "dry-run"],
    }).notNull(),
    status: text("status", {
      enum: ["pending", "running", "ok", "failed"],
    })
      .default("pending")
      .notNull(),
    startedAt: timestamp("started_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    durationMs: integer("duration_ms"),
    extracted: integer("extracted").default(0).notNull(),
    transformed: integer("transformed").default(0).notNull(),
    created: integer("created").default(0).notNull(),
    updated: integer("updated").default(0).notNull(),
    deleted: integer("deleted").default(0).notNull(),
    failed: integer("failed").default(0).notNull(),
    error: text("error"),
    metadata: jsonb("metadata"),
  },
  (table) => [
    index("khotan_runs_sync_id_idx").on(table.syncId),
    index("khotan_runs_status_idx").on(table.status),
    index("khotan_runs_sync_id_started_at_idx").on(
      table.syncId,
      table.startedAt.desc(),
    ),
  ],
);

// ---------------------------------------------------------------------------
// khotan_mappings — one row per entity instance within a resource
// ---------------------------------------------------------------------------

export const khotanMappings = pgTable(
  "khotan_mappings",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    resourceId: text("resource_id")
      .notNull()
      .references(() => khotanResources.id),
    connectValue: text("connect_value").notNull(),
    refs: jsonb("refs").notNull().$type<Record<string, string>>().default({}),
    metadata: jsonb("metadata").$type<Record<string, unknown>>(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    unique("khotan_mappings_resource_id_connect_value_unique").on(
      table.resourceId,
      table.connectValue,
    ),
    index("khotan_mappings_resource_id_idx").on(table.resourceId),
    index("khotan_mappings_refs_gin_idx").using("gin", table.refs),
  ],
);

// ---------------------------------------------------------------------------
// Relations
// ---------------------------------------------------------------------------

export const khotanPlugsRelations = relations(khotanPlugs, ({ many }) => ({
  syncs: many(khotanSyncs),
}));

export const khotanSyncsRelations = relations(
  khotanSyncs,
  ({ one, many }) => ({
    plug: one(khotanPlugs, {
      fields: [khotanSyncs.plugId],
      references: [khotanPlugs.id],
    }),
    resource: one(khotanResources, {
      fields: [khotanSyncs.resourceId],
      references: [khotanResources.id],
    }),
    runs: many(khotanRuns),
  }),
);

export const khotanRunsRelations = relations(khotanRuns, ({ one }) => ({
  sync: one(khotanSyncs, {
    fields: [khotanRuns.syncId],
    references: [khotanSyncs.id],
  }),
}));

export const khotanResourcesRelations = relations(
  khotanResources,
  ({ many }) => ({
    syncs: many(khotanSyncs),
    mappings: many(khotanMappings),
  }),
);

export const khotanMappingsRelations = relations(
  khotanMappings,
  ({ one }) => ({
    resource: one(khotanResources, {
      fields: [khotanMappings.resourceId],
      references: [khotanResources.id],
    }),
  }),
);

// ---------------------------------------------------------------------------
// Type helpers
// ---------------------------------------------------------------------------

export type KhotanPlug = typeof khotanPlugs.$inferSelect;
export type NewKhotanPlug = typeof khotanPlugs.$inferInsert;

export type KhotanSync = typeof khotanSyncs.$inferSelect;
export type NewKhotanSync = typeof khotanSyncs.$inferInsert;

export type KhotanRun = typeof khotanRuns.$inferSelect;
export type NewKhotanRun = typeof khotanRuns.$inferInsert;

export type KhotanResource = typeof khotanResources.$inferSelect;
export type NewKhotanResource = typeof khotanResources.$inferInsert;

export type KhotanMapping = typeof khotanMappings.$inferSelect;
export type NewKhotanMapping = typeof khotanMappings.$inferInsert;
