"use client";

import { useEffect, useState, useCallback } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

// ============================================================================
// Var Panel — UI for managing plug variables
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file is yours. Restyle, extend, or embed it however you like.
// It uses shadcn/ui primitives and fetches from /api/khotan/variables.
// ============================================================================

interface VarField {
  key: string;
  label: string;
  type: "text" | "password" | "url";
  secret?: boolean;
  hidden?: boolean;
  required?: boolean;
  placeholder?: string;
  defaultValue?: string;
}

interface VarPanelProps {
  plugName: string;
  label?: string;
  basePath?: string;
}

export function VarPanel({
  plugName,
  label,
  basePath = "/api/khotan",
}: VarPanelProps) {
  const displayName = label ?? plugName;
  const [fields, setFields] = useState<VarField[]>([]);
  const [values, setValues] = useState<Record<string, string>>({});
  const [formValues, setFormValues] = useState<Record<string, string>>({});
  const [configured, setConfigured] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [editing, setEditing] = useState(false);
  const [visibleSecrets, setVisibleSecrets] = useState<Record<string, boolean>>(
    {},
  );

  const fetchVariables = useCallback(async () => {
    try {
      const res = await fetch(`${basePath}/variables/${plugName}`);
      if (!res.ok) {
        setFields([]);
        setConfigured(false);
        return;
      }
      const data = await res.json();
      setFields((data.fields ?? []).filter((f: VarField) => !f.hidden));
      setValues(data.values ?? {});
      setConfigured(data.configured ?? false);
      setFormValues(data.configured ? data.values : {});
      setError(null);
    } catch {
      setError("Failed to load variables");
    } finally {
      setLoading(false);
    }
  }, [basePath, plugName]);

  useEffect(() => {
    fetchVariables();
  }, [fetchVariables]);

  async function handleSave() {
    setSaving(true);
    setError(null);
    setSuccess(null);
    try {
      const res = await fetch(`${basePath}/variables/${plugName}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(formValues),
      });

      if (!res.ok) {
        const data = await res.json();
        setError(data.error ?? "Failed to save variables");
        return;
      }

      setSuccess("Variables saved");
      setEditing(false);
      await fetchVariables();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Network error");
    } finally {
      setSaving(false);
    }
  }

  async function handleClear() {
    setSaving(true);
    setError(null);
    setSuccess(null);
    try {
      const res = await fetch(`${basePath}/variables/${plugName}`, {
        method: "DELETE",
      });

      if (!res.ok && res.status !== 204) {
        const data = await res.json();
        setError(data.error ?? "Failed to clear variables");
        return;
      }

      setSuccess("Variables cleared");
      setFormValues({});
      setEditing(false);
      await fetchVariables();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Network error");
    } finally {
      setSaving(false);
    }
  }

  if (loading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="text-sm font-medium capitalize">
            {displayName} Variables
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="h-4 w-2/3 animate-pulse rounded bg-muted" />
        </CardContent>
      </Card>
    );
  }

  if (fields.length === 0) return null;

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <CardTitle className="text-sm font-medium capitalize">
          {displayName} Variables
        </CardTitle>
        <Badge variant={configured ? "default" : "outline"}>
          {configured ? "Configured" : "Not Configured"}
        </Badge>
      </CardHeader>
      <CardContent className="space-y-4">
        {error && <p className="text-sm text-destructive">{error}</p>}
        {success && <p className="text-sm text-green-600">{success}</p>}

        {!editing && configured ? (
          <div className="space-y-3">
            <div className="text-xs text-muted-foreground space-y-1">
              {fields.map((field) => (
                <p key={field.key}>
                  <span className="font-medium">{field.label}:</span>{" "}
                  <code className="bg-muted px-1 py-0.5 rounded text-[11px]">
                    {field.secret ? "••••••••" : (values[field.key] ?? "—")}
                  </code>
                </p>
              ))}
            </div>
            <div className="flex gap-2">
              <Button
                size="sm"
                variant="outline"
                onClick={() => {
                  setEditing(true);
                  const prefilled: Record<string, string> = {};
                  for (const field of fields) {
                    if (!field.secret && values[field.key]) {
                      prefilled[field.key] = values[field.key];
                    }
                  }
                  setFormValues(prefilled);
                  setVisibleSecrets({});
                  setSuccess(null);
                }}
              >
                Update
              </Button>
              <Button
                size="sm"
                variant="destructive"
                onClick={handleClear}
                disabled={saving}
              >
                {saving ? "Clearing..." : "Clear"}
              </Button>
            </div>
          </div>
        ) : (
          <div className="space-y-3">
            {fields.map((field) => (
              <div key={field.key} className="space-y-1">
                <Label
                  htmlFor={`var-${plugName}-${field.key}`}
                  className="text-xs"
                >
                  {field.label}
                  {field.required !== false && (
                    <span className="text-destructive ml-0.5">*</span>
                  )}
                </Label>
                <div className="relative">
                  <Input
                    id={`var-${plugName}-${field.key}`}
                    type={
                      field.secret && !visibleSecrets[field.key]
                        ? "password"
                        : "text"
                    }
                    placeholder={
                      field.placeholder ??
                      (field.secret ? "Enter value..." : "")
                    }
                    value={formValues[field.key] ?? ""}
                    onChange={(e) =>
                      setFormValues((prev) => ({
                        ...prev,
                        [field.key]: e.target.value,
                      }))
                    }
                  />
                  {field.secret && (
                    <button
                      type="button"
                      className="absolute right-2 top-1/2 -translate-y-1/2 text-xs text-muted-foreground hover:text-foreground"
                      onClick={() =>
                        setVisibleSecrets((prev) => ({
                          ...prev,
                          [field.key]: !prev[field.key],
                        }))
                      }
                    >
                      {visibleSecrets[field.key] ? "Hide" : "Show"}
                    </button>
                  )}
                </div>
              </div>
            ))}
            <div className="flex gap-2">
              <Button size="sm" onClick={handleSave} disabled={saving}>
                {saving ? "Saving..." : "Save Variables"}
              </Button>
              {editing && (
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => {
                    setEditing(false);
                    setSuccess(null);
                  }}
                >
                  Cancel
                </Button>
              )}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
