// ============================================================================
// Wire — webhook subscription lifecycle hooks
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file defines the wire() builder and types. Create per-service wire
// files (e.g. pollinate-wire.ts) using this builder to handle subscribe,
// unsubscribe, and verification logic for each external service.
//
// Wire hooks receive a "bound plug" — the plug with vars and auth
// auto-injected by the factory. Just call ctx.plug.post/delete/etc.
// ============================================================================

import type { Plug } from "../plugs/plug";

// ---------------------------------------------------------------------------
// Bound Plug — plug with vars auto-injected by the factory
// ---------------------------------------------------------------------------

export interface BoundPlug {
  readonly name: string;
  readonly baseUrl: string;
  get<T>(path: string, options?: { params?: Record<string, unknown>; headers?: Record<string, string> }): Promise<T>;
  post<T>(path: string, options?: { body?: unknown; headers?: Record<string, string> }): Promise<T>;
  put<T>(path: string, options?: { body?: unknown; headers?: Record<string, string> }): Promise<T>;
  patch<T>(path: string, options?: { body?: unknown; headers?: Record<string, string> }): Promise<T>;
  delete<T>(path: string, options?: { headers?: Record<string, string> }): Promise<T>;
}

// ---------------------------------------------------------------------------
// Hook Contexts
// ---------------------------------------------------------------------------

export interface WireSubscribeContext {
  /** Plug instance with vars and auth auto-injected */
  plug: BoundPlug;
  /** The callback URL to register with the external service */
  callbackUrl: string;
  /** Event types this wire subscribes to */
  events: string[];
  /** Previously stored wire-specific vars (empty on first subscribe) */
  wireVars: Record<string, string>;
  /** Persist wire-specific vars (webhook secrets, tokens, etc.) */
  setWireVars(updates: Record<string, string>): Promise<void>;
}

export interface WireUnsubscribeContext {
  /** Plug instance with vars and auth auto-injected */
  plug: BoundPlug;
  /** The remote subscription ID returned from onSubscribe */
  remoteId: string;
  /** Wire-specific vars stored during subscribe */
  wireVars: Record<string, string>;
  /** Persist wire-specific var updates */
  setWireVars(updates: Record<string, string>): Promise<void>;
}

export interface WireVerifyContext {
  /** Incoming request headers */
  headers: Headers;
  /** Raw request body (string or parsed object) */
  body: unknown;
  /** Wire-specific vars (e.g. webhook signing secret) */
  wireVars: Record<string, string>;
}

// ---------------------------------------------------------------------------
// Wire Config
// ---------------------------------------------------------------------------

export interface WireConfig {
  /** Event types this wire subscribes to */
  events: string[];

  /**
   * Called when the wire is being connected.
   * Make the API call to register the webhook subscription and return the remoteId.
   */
  onSubscribe(ctx: WireSubscribeContext): Promise<{ remoteId: string }>;

  /**
   * Called when the wire is being disconnected.
   * Make the API call to remove the webhook subscription.
   */
  onUnsubscribe(ctx: WireUnsubscribeContext): Promise<void>;

  /**
   * Optional: verify incoming webhook signatures.
   * Return true if the signature is valid.
   */
  onVerify?(ctx: WireVerifyContext): Promise<boolean>;
}

// ---------------------------------------------------------------------------
// Builder
// ---------------------------------------------------------------------------

export function wire(config: WireConfig): WireConfig {
  return config;
}

// ---------------------------------------------------------------------------
// Usage Example (create a file like wires/stripe-wire.ts)
// ---------------------------------------------------------------------------
//
// import { wire } from "./wire";
//
// export const stripeWire = wire({
//   events: ["invoice.paid", "invoice.payment_failed"],
//
//   async onSubscribe(ctx) {
//     const res = await ctx.plug.post<{ id: string; secret: string }>(
//       "/webhook_endpoints",
//       {
//         body: {
//           url: ctx.callbackUrl,
//           enabled_events: ctx.events,
//         },
//       },
//     );
//
//     // Store the webhook signing secret for verification
//     await ctx.setWireVars({ webhookSecret: res.secret });
//
//     return { remoteId: res.id };
//   },
//
//   async onUnsubscribe(ctx) {
//     await ctx.plug.delete(`/webhook_endpoints/${ctx.remoteId}`);
//   },
//
//   async onVerify(ctx) {
//     const signature = ctx.headers.get("stripe-signature");
//     if (!signature) return false;
//     // Verify using ctx.wireVars.webhookSecret
//     return true;
//   },
// });
