"use client";

import { useEffect, useState, useCallback } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

// ============================================================================
// Wire Panel — UI for managing webhook subscriptions
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file is yours. Restyle, extend, or embed it however you like.
// It uses shadcn/ui primitives and fetches from /api/khotan/wires.
// ============================================================================

interface WireRecord {
  id: string;
  plugId: string;
  remoteId: string;
  callbackUrl: string;
  eventTypes: string[];
  status: "active" | "disabled" | "pending";
  createdAt: string;
  updatedAt: string;
}

interface WirePanelProps {
  plugName: string;
  label?: string;
  basePath?: string;
  webhookUrl?: string;
}

export function WirePanel({ plugName, label, basePath = "/api/khotan", webhookUrl }: WirePanelProps) {
  const displayName = label ?? plugName;
  const resolvedWebhookUrl = webhookUrl || (typeof window !== "undefined" ? window.location.origin : "");
  const [wire, setWire] = useState<WireRecord | null>(null);
  const [configured, setConfigured] = useState(false);
  const [loading, setLoading] = useState(true);
  const [acting, setActing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchWire = useCallback(async () => {
    try {
      const res = await fetch(`${basePath}/wires/${plugName}`);
      if (!res.ok) {
        setConfigured(false);
        setWire(null);
        return;
      }
      const data = await res.json();
      setConfigured(data.configured ?? false);
      setWire(data.wire ?? null);
      setError(null);
    } catch {
      setConfigured(false);
    } finally {
      setLoading(false);
    }
  }, [basePath, plugName]);

  useEffect(() => {
    fetchWire();
  }, [fetchWire]);

  async function handleCreate() {
    setActing(true);
    setError(null);
    try {
      const callbackUrl = `${resolvedWebhookUrl}/api/${plugName}/webhook`;

      const res = await fetch(`${basePath}/wires/${plugName}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ callbackUrl }),
      });

      if (!res.ok) {
        const data = await res.json();
        setError(data.error ?? "Failed to create wire");
        return;
      }

      const data = await res.json();
      setWire(data.wire ?? null);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Network error");
    } finally {
      setActing(false);
    }
  }

  async function handleDelete() {
    if (!wire) return;
    setActing(true);
    setError(null);
    try {
      const res = await fetch(`${basePath}/wires/${plugName}`, {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ wireId: wire.id }),
      });

      if (!res.ok && res.status !== 204) {
        const data = await res.json();
        setError(data.error ?? "Failed to disconnect");
        return;
      }

      await fetchWire();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Network error");
    } finally {
      setActing(false);
    }
  }

  if (loading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="text-sm font-medium capitalize">
            {displayName} Wire
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="h-4 w-2/3 animate-pulse rounded bg-muted" />
        </CardContent>
      </Card>
    );
  }

  if (!configured) return null;

  const isActive = wire?.status === "active";
  const isPending = wire?.status === "pending";

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <CardTitle className="text-sm font-medium capitalize">
          {displayName} Wire
        </CardTitle>
        <Badge variant={isActive ? "default" : isPending ? "outline" : "secondary"}>
          {isActive ? "Connected" : isPending ? "Not Connected" : "Disconnected"}
        </Badge>
      </CardHeader>
      <CardContent className="space-y-3">
        {error && (
          <p className="text-sm text-destructive">{error}</p>
        )}

        {isActive ? (
          <div className="space-y-2">
            <div className="text-xs text-muted-foreground space-y-1">
              <p>
                <span className="font-medium">Callback:</span>{" "}
                <code className="bg-muted px-1 py-0.5 rounded text-[11px]">
                  {wire!.callbackUrl}
                </code>
              </p>
              <p>
                <span className="font-medium">Remote ID:</span>{" "}
                <code className="bg-muted px-1 py-0.5 rounded text-[11px]">
                  {wire!.remoteId}
                </code>
              </p>
              <p>
                <span className="font-medium">Events:</span>{" "}
                {wire!.eventTypes.join(", ")}
              </p>
              <p>
                <span className="font-medium">Created:</span>{" "}
                {new Date(wire!.createdAt).toLocaleString()}
              </p>
            </div>
            <Button
              variant="destructive"
              size="sm"
              onClick={handleDelete}
              disabled={acting}
            >
              {acting ? "Disconnecting..." : "Disconnect"}
            </Button>
          </div>
        ) : (
          <div className="space-y-2">
            <p className="text-xs text-muted-foreground">
              No active webhook subscription. Click below to register one with{" "}
              <span className="capitalize">{displayName}</span>.
            </p>
            <p className="text-xs text-muted-foreground">
              <span className="font-medium">Webhook URL:</span>{" "}
              <code className="bg-muted px-1 py-0.5 rounded text-[11px]">
                {resolvedWebhookUrl}/api/{plugName}/webhook
              </code>
            </p>
            <Button
              size="sm"
              onClick={handleCreate}
              disabled={acting}
            >
              {acting ? "Connecting..." : "Connect Webhook"}
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
