// ============================================================================
// Wire — webhook subscription lifecycle hooks
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file defines the wire() builder and types. Create per-service wire
// files (e.g. pollinate-wire.ts) using this builder to handle subscribe,
// unsubscribe, and verification logic for each external service.
//
// Wire hooks receive a "bound plug" — the plug with vars and auth
// auto-injected by the factory. Just call ctx.plug.post/delete/etc.
// ============================================================================

import type { Plug } from "../plugs/plug";
import { verifyHmacSha256 } from "khotan-data/factory";

// ---------------------------------------------------------------------------
// Bound Plug — plug with vars auto-injected by the factory
// ---------------------------------------------------------------------------

export interface BoundPlug {
  readonly name: string;
  readonly baseUrl: string;
  get<T>(
    path: string,
    options?: {
      params?: Record<string, unknown>;
      headers?: Record<string, string>;
    },
  ): Promise<T>;
  post<T>(
    path: string,
    options?: {
      body?: unknown;
      headers?: Record<string, string>;
      signal?: AbortSignal;
    },
  ): Promise<T>;
  batchPost<TResponse = unknown, TRecord = unknown>(
    path: string,
    records: readonly TRecord[],
    options?: {
      batchSize?: number;
      concurrency?: number;
      headers?: Record<string, string>;
      signal?: AbortSignal;
      buildBody?: (records: TRecord[], batchIndex: number) => unknown;
    },
  ): Promise<TResponse[]>;
  put<T>(
    path: string,
    options?: {
      body?: unknown;
      headers?: Record<string, string>;
      signal?: AbortSignal;
    },
  ): Promise<T>;
  patch<T>(
    path: string,
    options?: {
      body?: unknown;
      headers?: Record<string, string>;
      signal?: AbortSignal;
    },
  ): Promise<T>;
  delete<T>(
    path: string,
    options?: { headers?: Record<string, string>; signal?: AbortSignal },
  ): Promise<T>;
}

// ---------------------------------------------------------------------------
// Hook Contexts
// ---------------------------------------------------------------------------

export interface WireSubscribeContext {
  /** Plug instance with vars and auth auto-injected */
  plug: BoundPlug;
  /** The callback URL to register with the external service */
  callbackUrl: string;
  /** Event types this wire subscribes to */
  events: string[];
  /** Previously stored wire-specific vars (empty on first subscribe) */
  wireVars: Record<string, string>;
  /** Persist wire-specific vars (webhook secrets, tokens, etc.) */
  setWireVars(updates: Record<string, string>): Promise<void>;
}

export interface WireUnsubscribeContext {
  /** Plug instance with vars and auth auto-injected */
  plug: BoundPlug;
  /** The remote subscription ID returned from onSubscribe */
  remoteId: string;
  /** Wire-specific vars stored during subscribe */
  wireVars: Record<string, string>;
  /** Persist wire-specific var updates */
  setWireVars(updates: Record<string, string>): Promise<void>;
}

export interface WireVerifyContext {
  /** Incoming request headers as plain key-value pairs */
  headers: Record<string, string>;
  /** Raw request body as text (for signature verification) */
  body: string;
  /** Wire-specific vars (e.g. webhook signing secret) */
  wireVars: Record<string, string>;
}

export interface WireRenewContext extends WireSubscribeContext {
  /** The current remote subscription ID */
  remoteId: string;
  /** Last known subscription expiry, when the provider has one */
  expiresAt?: string | null;
}

export interface WireSubscribeResult {
  remoteId: string;
  expiresAt?: string | Date | null;
}

export interface WireRenewResult {
  remoteId?: string;
  expiresAt?: string | Date | null;
}

// ---------------------------------------------------------------------------
// Wire Config
// ---------------------------------------------------------------------------

export interface WireConfig {
  /** Event types this wire subscribes to */
  events: string[];

  /**
   * "managed" wires call onSubscribe/onUnsubscribe against the provider.
   * "manual" wires only store the callback URL for providers that require
   * webhook registration in their dashboard.
   */
  mode?: "managed" | "manual";

  /**
   * Called when the wire is being connected.
   * Make the API call to register the webhook subscription and return the remoteId.
   */
  onSubscribe?(ctx: WireSubscribeContext): Promise<WireSubscribeResult>;

  /**
   * Called when the wire is being disconnected.
   * Make the API call to remove the webhook subscription.
   */
  onUnsubscribe?(ctx: WireUnsubscribeContext): Promise<void>;

  /**
   * Optional: renew a provider subscription before it expires.
   * Khotan exposes this through wire().renew() and POST /wires/:plugName/renew.
   */
  onRenew?(ctx: WireRenewContext): Promise<WireRenewResult>;

  /**
   * Optional: verify incoming webhook signatures.
   * Return true if the signature is valid.
   */
  onVerify?(ctx: WireVerifyContext): Promise<boolean>;
}

// ---------------------------------------------------------------------------
// Builder
// ---------------------------------------------------------------------------

export function wire(config: WireConfig): WireConfig {
  return config;
}

// ---------------------------------------------------------------------------
// Usage Example (create a file like wires/stripe-wire.ts)
// ---------------------------------------------------------------------------
//
// import { wire, verifyHmacSha256 } from "./wire";
//
// export const stripeWire = wire({
//   events: ["invoice.paid", "invoice.payment_failed"],
//
//   async onSubscribe(ctx) {
//     const res = await ctx.plug.post<{ id: string; secret: string }>(
//       "/webhook_endpoints",
//       {
//         body: {
//           url: ctx.callbackUrl,
//           enabled_events: ctx.events,
//         },
//       },
//     );
//
//     // Store the webhook signing secret for verification
//     await ctx.setWireVars({ webhookSecret: res.secret });
//
//     return { remoteId: res.id };
//   },
//
//   async onUnsubscribe(ctx) {
//     await ctx.plug.delete(`/webhook_endpoints/${ctx.remoteId}`);
//   },
//
//   async onVerify(ctx) {
//     const signature = ctx.headers["stripe-signature"];
//     if (!signature) return false;
//     return verifyHmacSha256(ctx.body, signature, ctx.wireVars.webhookSecret, {
//       digest: "hex",
//       prefix: "sha256=",
//     });
//   },
// });

export { verifyHmacSha256 };
