// ============================================================================
// Wire — webhook subscription lifecycle hooks
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file keeps local imports stable while reusing the real builder and types
// from khotan-data/factory. Create per-service wire files using wire() to handle
// subscribe, unsubscribe, and verification logic for each external service.
// ============================================================================

export { wire, verifyHmacSha256 } from "khotan-data/factory";

export type {
  BoundPlug,
  WireConfig,
  WireRegistration,
  WireSubscribeContext,
  WireUnsubscribeContext,
  WireVerifyContext,
  WireRenewContext,
  WireSubscribeResult,
  WireRenewResult,
} from "khotan-data/factory";

// ---------------------------------------------------------------------------
// Usage Example (create a file like wires/stripe-wire.ts)
// ---------------------------------------------------------------------------
//
// import { wire, verifyHmacSha256 } from "./wire";
//
// export const stripeWire = wire({
//   events: ["invoice.paid", "invoice.payment_failed"],
//
//   async onSubscribe(ctx) {
//     const res = await ctx.plug.post<{ id: string; secret: string }>(
//       "/webhook_endpoints",
//       {
//         body: {
//           url: ctx.callbackUrl,
//           enabled_events: ctx.events,
//         },
//       },
//     );
//
//     // Store the webhook signing secret for verification
//     await ctx.setWireVars({ webhookSecret: res.secret });
//
//     return { remoteId: res.id };
//   },
//
//   async onUnsubscribe(ctx) {
//     await ctx.plug.delete(`/webhook_endpoints/${ctx.remoteId}`);
//   },
//
//   async onVerify(ctx) {
//     const signature = ctx.headers["stripe-signature"];
//     if (!signature) return false;
//     return verifyHmacSha256(ctx.body, signature, ctx.wireVars.webhookSecret, {
//       digest: "hex",
//       prefix: "sha256=",
//     });
//   },
// });

export { verifyHmacSha256 };
